SPUI-264 > Buy: Choose payment method
MyJetWallet/Flutter.JetWallet pull request #115
Opened 2021-08-05 11:28 UTC by eli1stark

2021-08-05 14:31 UTC, VovaMedvediev requested changes

2021-08-05 14:31 UTC, VovaMedvediev commented on lib/app/shared/components/action_sheet_button.dart
> +                height: 32.w,
h

2021-08-05 14:31 UTC, VovaMedvediev commented on lib/app/shared/components/basic_bottom_sheet/basic_bottom_sheet.dart
> +    isScrollControlled: true,
(optional) maybe we can use a more understandable name?

2021-08-05 14:31 UTC, VovaMedvediev commented on lib/app/shared/components/basic_bottom_sheet/basic_bottom_sheet.dart
> +        return Future.value();
i think it can be refactored

2021-08-05 14:31 UTC, VovaMedvediev commented on lib/app/shared/components/basic_bottom_sheet/basic_bottom_sheet.dart
> +      Navigator.pop(context);
maybe we can refactor all Navigator actions to one class (singleton maybe)? So they are in one place

2021-08-05 14:31 UTC, VovaMedvediev commented on lib/app/shared/features/currency_buy/view/components/asset_tile/asset_tile.dart
> +                height: 30.w,
h?

2021-08-05 14:31 UTC, VovaMedvediev commented on lib/app/shared/features/currency_buy/view/curency_buy.dart
> +              // ignore: avoid_print
?

2021-08-06 03:58 UTC, eli1stark commented on lib/app/shared/components/action_sheet_button.dart
> +                height: 32.w,
it's a square

2021-08-06 03:59 UTC, eli1stark commented on lib/app/shared/components/basic_bottom_sheet/basic_bottom_sheet.dart
> +    isScrollControlled: true,
it's Flutter's component)

2021-08-06 04:01 UTC, eli1stark commented on lib/app/shared/features/currency_buy/view/components/asset_tile/asset_tile.dart
> +                height: 30.w,
it's a square

2021-08-06 04:01 UTC, eli1stark commented on lib/app/shared/features/currency_buy/view/curency_buy.dart
> +              // ignore: avoid_print
in development

2021-08-06 04:04 UTC, eli1stark commented on lib/app/shared/components/basic_bottom_sheet/basic_bottom_sheet.dart
> +      Navigator.pop(context);
We have it, it's called Navigator from Flutter. And for simple actions like pop, it doesn't make any sense. This will be probably a good idea for complex navigation methods.

2021-08-06 04:06 UTC, eli1stark commented on lib/app/shared/components/basic_bottom_sheet/basic_bottom_sheet.dart
> +        return Future.value();
it's already refactored, no? `return Future.value();` is specific to `onWillPop`

2021-08-06 04:06 UTC, eli1stark commented on lib/app/shared/features/currency_buy/view/components/asset_tile/asset_tile.dart
> +                height: 30.w,
Additional note, if you will be constructing squares in the future, use the same aproach

2021-08-06 11:22 UTC, merged