Feat/spu 3149/send gift start flow
MyJetWallet/Flutter.JetWallet pull request #1243
Opened 2023-07-20 07:24 UTC by 40rty5ive

2023-08-15 11:15 UTC, gravio-inv requested changes

2023-08-15 11:15 UTC, gravio-inv commented on lib/features/send_gift/widgets/gift_send_type.dart
> +                    color: Color(0xFF374CFA),
ui kit

2023-08-15 11:15 UTC, gravio-inv commented on lib/features/send_gift/widgets/gift_send_type.dart
> +                const SpaceW19(), // + 1px border
Лишний комментарий

2023-08-15 11:15 UTC, gravio-inv commented on lib/features/send_gift/widgets/share_gift_result_bottom_sheet.dart
> +                            style: const TextStyle(
ui kit

2023-08-15 11:15 UTC, gravio-inv commented on lib/features/send_gift/widgets/share_gift_result_bottom_sheet.dart
> +                              style: const TextStyle(
ui kit

2023-08-15 11:15 UTC, gravio-inv commented on lib/features/send_gift/widgets/share_gift_result_bottom_sheet.dart
> +                              style: const TextStyle(
UI KIT

2023-08-15 11:15 UTC, gravio-inv commented on lib/features/send_gift/widgets/share_gift_result_bottom_sheet.dart
> +                                        style: const TextStyle(
UI KIT

2023-08-15 11:15 UTC, gravio-inv commented on lib/features/send_gift/widgets/share_gift_result_bottom_sheet.dart
> +                                        style: const TextStyle(
UI KIT

2023-08-15 11:15 UTC, gravio-inv commented on lib/features/wallet/ui/widgets/wallet_body/widgets/transactions_list_item/components/transaction_details/gift_send_details.dart
> +    final store = StackLoaderStore();
Лодер больше не инцилизируем в ui, тем более в build

2023-08-16 10:59 UTC, 40rty5ive commented on lib/features/send_gift/store/receiver_datails_store.dart
> +    emailValid = isEmailValid(email);
Мне не всегда нужно показывать ошибку на поле емейла, а после некоторых действий

2023-08-17 08:08 UTC, gravio-inv approved these changes

2023-08-17 08:08 UTC, merged