SPUI-175 > Feature/watchlist
MyJetWallet/Flutter.JetWallet pull request #126
Opened 2021-08-22 06:56 UTC by VovaMedvediev

2021-08-23 10:40 UTC, eli1stark commented on lib/app/screens/market/notifier/watchlist_notifier.dart
> +      final set = Set.of(state);
Why are you using set?

2021-08-23 10:46 UTC, eli1stark commented on lib/app/screens/market/notifier/watchlist_notifier.dart
> +      _logger.log(notifier, 'removeFromWatchlist', e);
Add `_logger.log(stateFlow, 'verifyCode', e);`

2021-08-23 10:47 UTC, eli1stark commented on lib/app/screens/market/notifier/watchlist_notifier.dart
> +    _logger.log(notifier, 'isInWatchlist');
The same here

2021-08-23 10:47 UTC, eli1stark commented on lib/app/screens/market/notifier/watchlist_notifier.dart
> +      _logger.log(notifier, 'changePosition', e);
The same here

2021-08-23 10:49 UTC, eli1stark commented on lib/app/screens/market/notifier/watchlist_notifier.dart
> +const watchlistKey = 'watchlist';
maybe move all keys to the more apropriate place? For exmaple to KeyValue

2021-08-23 10:51 UTC, eli1stark commented on lib/app/screens/market/notifier/watchlist_notipod.dart
> +        keyValue.watchlist != null ? keyValue.watchlist!.value : <String>[];
Try to replace to:
`final watchList = keyValue.watchlist?.value ?? <String>[];`

2021-08-23 10:55 UTC, eli1stark commented on lib/app/screens/market/provider/market_watchlist_items_pod.dart
> +  final watchlistIds = ref.watch(watchlistNotipod);
maybe rename `watchlistNotipod` to `watchlistIdsNotipod` to keep clarity?

2021-08-23 10:56 UTC, eli1stark commented on lib/app/screens/market/provider/market_watchlist_items_pod.dart
> +  final notifier = ref.watch(watchlistNotipod.notifier);
rename notifier to watchlistIdsN

2021-08-23 10:57 UTC, eli1stark commented on lib/app/screens/market/provider/market_watchlist_items_pod.dart
> +  for (final watchlistId in watchlistIds) {
for (final id in watchlistIds)

2021-08-23 10:58 UTC, eli1stark commented on lib/app/screens/market/provider/market_watchlist_items_pod.dart
> +    for (final watchlistItem in watchlistItems) {
for (final item in watchlistItems) {

2021-08-23 11:01 UTC, eli1stark commented on lib/app/screens/market/view/components/market_tab_content/components/empty_watchlist.dart
> +          size: 0.3.sw,
0.3.r

2021-08-23 11:01 UTC, eli1stark commented on lib/app/screens/market/view/components/market_tab_content/components/empty_watchlist.dart
> +        const Text('Star an asset to add it to your Watchlist'),
comma

2021-08-23 11:03 UTC, eli1stark commented on lib/app/screens/market/view/components/market_tab_content/components/market_reordable_list.dart
> +            key: Key('${items[index].weight}'),
comma

2021-08-23 11:05 UTC, eli1stark commented on lib/app/screens/market/view/components/market_tab_content/market_tab_content.dart
> +    this.isWatchlist = false,
"is" is suitable more for functions.
For paremeters better to use just name without "is".
Exmaple: `isWatchlist` to `watchlist`.

2021-08-23 11:08 UTC, eli1stark commented on lib/app/screens/market/view/components/market_tab_content/market_tab_content.dart
>      required this.items,
place `required` parameters always last by flutter convention.

2021-08-23 11:11 UTC, eli1stark commented on lib/app/screens/market/view/components/market_tabs/market_tabs.dart
>          margin: EdgeInsets.only(bottom: 16.h),
comma

2021-08-23 11:11 UTC, eli1stark commented on lib/app/screens/market/view/components/market_tabs/market_tabs.dart
>                Radius.circular(30),
make responsive (30.r)

2021-08-23 11:13 UTC, eli1stark commented on lib/app/screens/market/view/market.dart
> +  int _marketTabsLength(bool isGainersEmpty, bool isLoosersEmpty) {
gainersEmpty, loosersEmpty

2021-08-23 11:17 UTC, eli1stark commented on lib/app/screens/market_details/provider/news_notipod.dart
move news_notipod to notifier folder

2021-08-23 11:21 UTC, eli1stark commented on lib/app/shared/features/key_value/notifier/key_value_notifier.dart
> +        )) {
comma

2021-08-23 11:22 UTC, eli1stark commented on lib/app/shared/features/key_value/notifier/key_value_notifier.dart
> +      _logger.log(notifier, 'addToKeyValue', e);
wrong log

2021-08-23 11:22 UTC, eli1stark commented on lib/app/shared/features/key_value/notifier/key_value_notifier.dart
> +      _logger.log(notifier, 'removeFromKeyValue', e);
wrong log

2021-08-23 11:42 UTC, eli1stark commented on lib/service/services/market_info/market_info_service.dart
> +class MarketInfoService {
`MarketInfoResponseModel` has `whitepaperUrl` parameter.
It's required and nullable at the same time.
It can be one of them but not both.

2021-08-23 13:49 UTC, eli1stark commented on lib/service/services/signal_r/model/key_value_model.dart
> +    WatchlistModel? watchlist,
required parameters must go last

2021-08-23 13:55 UTC, eli1stark commented on lib/service/services/signal_r/model/key_value_model.dart
> +  factory WatchlistModel.fromJson(Map<String, dynamic> json) =>
This is wrong serialization. First of all it's manual, second, you are just casting to the String, this doesn't bring any value. How do you parse this value on UI?

2021-08-23 13:57 UTC, eli1stark commented on lib/service/services/signal_r/service/signal_r_service.dart
> +  KeyValueModel _serializeKeys(KeyValueModel keyValue) {
doesn't belong here

2021-08-23 13:58 UTC, eli1stark commented on lib/service/services/signal_r/service/signal_r_service.dart
> +        final keyValue = KeyValueModel.fromJson(_json(data));
this line of code should do all the stuff. Other implementation details doesn't belong to SignalRService

2021-08-23 13:58 UTC, eli1stark commented on lib/service/services/signal_r/service/signal_r_service.dart
> +        final serializedKeyValue = _serializeKeys(keyValue);
doesn't belong here

2021-08-23 14:06 UTC, eli1stark commented on lib/service/services/signal_r/service/signal_r_service.dart
> +      if (keyValuePair.key == watchlistKey) {
move watchlistKey from notifier to KeyValue service folder.
for example: services/key_value/key_value_keys.dart

2021-08-23 14:11 UTC, eli1stark commented on lib/service/services/key_value/key_value_service.dart
> +  Future<void> keyValueRemove(List<String> keys) {
rename to removeKtyValue

2021-08-23 14:11 UTC, eli1stark commented on lib/service/services/key_value/key_value_service.dart
> +  Future<void> keyValueSet(KeyValueRequestModel model) {
rename to setKeyValue

2021-08-23 14:13 UTC, eli1stark commented on lib/service/services/key_value/key_value_service.dart
> +class KeyValueService {
where is getKeyValue method?

2021-08-23 14:15 UTC, eli1stark commented on lib/service/services/signal_r/model/key_value_model.dart
> +class KeyValuePairModel with _$KeyValuePairModel {
`KeyValueResponseModel` and `KeyValuePairModel` are the same

2021-08-23 14:20 UTC, eli1stark requested changes
Add 31 comment

2021-08-30 16:23 UTC, VovaMedvediev commented on lib/app/screens/market/notifier/watchlist_notifier.dart
> +      final set = Set.of(state);
In order to have unique values (set doesn't support duplicates)

2021-08-30 16:24 UTC, VovaMedvediev commented on lib/app/screens/market/notifier/watchlist_notifier.dart
> +      _logger.log(notifier, 'removeFromWatchlist', e);
done

2021-08-30 16:24 UTC, VovaMedvediev commented on lib/app/screens/market/notifier/watchlist_notifier.dart
> +      _logger.log(notifier, 'changePosition', e);
done

2021-08-30 16:36 UTC, VovaMedvediev commented on lib/app/screens/market/notifier/watchlist_notifier.dart
> +const watchlistKey = 'watchlist';
moved to key_value/model/key_value_key.dart

2021-08-30 16:36 UTC, VovaMedvediev commented on lib/app/screens/market/notifier/watchlist_notipod.dart
> +        keyValue.watchlist != null ? keyValue.watchlist!.value : <String>[];
replaced

2021-08-30 16:36 UTC, VovaMedvediev commented on lib/app/screens/market/provider/market_watchlist_items_pod.dart
> +  final watchlistIds = ref.watch(watchlistNotipod);
done

2021-08-30 16:37 UTC, VovaMedvediev commented on lib/app/screens/market/provider/market_watchlist_items_pod.dart
> +  final notifier = ref.watch(watchlistNotipod.notifier);
done

2021-08-30 16:38 UTC, VovaMedvediev commented on lib/app/screens/market/provider/market_watchlist_items_pod.dart
> +  for (final watchlistId in watchlistIds) {
refactored

2021-08-30 16:38 UTC, VovaMedvediev commented on lib/app/screens/market/provider/market_watchlist_items_pod.dart
> +    for (final watchlistItem in watchlistItems) {
refactored

2021-08-30 16:43 UTC, VovaMedvediev commented on lib/app/screens/market/view/components/market_tab_content/components/empty_watchlist.dart
> +          size: 0.3.sw,
0.3.r is a different size. I think it'll be refactored when final UI will be ready

2021-08-30 16:43 UTC, VovaMedvediev commented on lib/app/screens/market/view/components/market_tab_content/components/empty_watchlist.dart
> +        const Text('Star an asset to add it to your Watchlist'),
done

2021-08-30 16:44 UTC, VovaMedvediev commented on lib/app/screens/market/view/components/market_tab_content/components/market_reordable_list.dart
> +            key: Key('${items[index].weight}'),
done

2021-08-30 16:44 UTC, VovaMedvediev commented on lib/app/screens/market/view/components/market_tab_content/market_tab_content.dart
> +    this.isWatchlist = false,
renamed

2021-08-30 16:45 UTC, VovaMedvediev commented on lib/app/screens/market/view/components/market_tab_content/market_tab_content.dart
>      required this.items,
refactored

2021-08-30 16:46 UTC, VovaMedvediev commented on lib/app/screens/market/view/components/market_tabs/market_tabs.dart
>          margin: EdgeInsets.only(bottom: 16.h),
done

2021-08-30 16:47 UTC, VovaMedvediev commented on lib/app/screens/market/view/components/market_tabs/market_tabs.dart
>                Radius.circular(30),
done

2021-08-30 16:47 UTC, VovaMedvediev commented on lib/app/screens/market/view/market.dart
> +  int _marketTabsLength(bool isGainersEmpty, bool isLoosersEmpty) {
renamed

2021-08-30 16:48 UTC, VovaMedvediev commented on lib/app/screens/market_details/provider/news_notipod.dart
moved

2021-08-30 16:48 UTC, VovaMedvediev commented on lib/app/shared/features/key_value/notifier/key_value_notifier.dart
> +        )) {
done

2021-08-30 17:14 UTC, VovaMedvediev commented on lib/app/shared/features/key_value/notifier/key_value_notifier.dart
> +      _logger.log(notifier, 'addToKeyValue', e);
fixed

2021-08-30 17:14 UTC, VovaMedvediev commented on lib/app/shared/features/key_value/notifier/key_value_notifier.dart
> +      _logger.log(notifier, 'removeFromKeyValue', e);
fixed

2021-08-30 17:17 UTC, VovaMedvediev commented on lib/service/services/market_info/market_info_service.dart
> +class MarketInfoService {
required removed

2021-08-30 17:18 UTC, VovaMedvediev commented on lib/service/services/signal_r/model/key_value_model.dart
> +    WatchlistModel? watchlist,
done

2021-08-30 17:29 UTC, VovaMedvediev commented on lib/service/services/signal_r/service/signal_r_service.dart
> +  KeyValueModel _serializeKeys(KeyValueModel keyValue) {
moved to KeyValueModel.fromModel (factory constructor)

2021-08-30 17:29 UTC, VovaMedvediev commented on lib/service/services/signal_r/service/signal_r_service.dart
> +        final keyValue = KeyValueModel.fromJson(_json(data));
refactored

2021-08-30 17:30 UTC, VovaMedvediev commented on lib/service/services/signal_r/service/signal_r_service.dart
> +        final serializedKeyValue = _serializeKeys(keyValue);
moved to KeyValueModel.fromModel (factory constructor)

2021-08-30 17:30 UTC, VovaMedvediev commented on lib/service/services/signal_r/service/signal_r_service.dart
> +      if (keyValuePair.key == watchlistKey) {
moved to app/shared/features/key_value/model/key_value_key.dart

2021-08-30 17:31 UTC, VovaMedvediev commented on lib/service/services/key_value/key_value_service.dart
> +  Future<void> keyValueRemove(List<String> keys) {
renamed

2021-08-30 17:31 UTC, VovaMedvediev commented on lib/service/services/key_value/key_value_service.dart
> +  Future<void> keyValueSet(KeyValueRequestModel model) {
renamed

2021-08-30 17:32 UTC, VovaMedvediev commented on lib/service/services/key_value/key_value_service.dart
> +class KeyValueService {
It was developed for debugging purposes. In order to get keyValue it is needed to listen to it from signal_r

2021-08-30 17:37 UTC, VovaMedvediev commented on lib/service/services/signal_r/model/key_value_model.dart
> +class KeyValuePairModel with _$KeyValuePairModel {
KeyValuePairModel is removed. KeyValueResponseModel used instead

2021-08-31 08:10 UTC, eli1stark commented on lib/app/screens/market/notifier/watchlist_notifier.dart
> +const watchlistKey = 'watchlist';
better to move them to `key_value/keys.dart`

2021-08-31 08:25 UTC, eli1stark commented on lib/app/screens/market/view/components/market_tab_content/components/empty_watchlist.dart
> +          size: 0.3.sw,
The recommended practice for a single size like `Icon` is `.r`

2021-08-31 08:35 UTC, eli1stark commented on lib/service/services/signal_r/service/signal_r_service.dart
> +  KeyValueModel _serializeKeys(KeyValueModel keyValue) {
Rename to `fromJson`.
And can you make the code below:
```
final keyValue = KeyValueModel.fromModel(
  KeyValueModel.fromJson(
    _json(data),
  ),
);
```
look like this:
```
final keyValue = KeyValueModel.fromJson( _json(data));
```

2021-08-31 08:36 UTC, eli1stark commented on lib/service/services/signal_r/service/signal_r_service.dart
> +  KeyValueModel _serializeKeys(KeyValueModel keyValue) {
hide complexity in the model

2021-08-31 09:14 UTC, VovaMedvediev commented on lib/app/screens/market/notifier/watchlist_notifier.dart
> +const watchlistKey = 'watchlist';
moved to service/shared/constants.dart

2021-08-31 09:17 UTC, VovaMedvediev commented on lib/app/screens/market/view/components/market_tab_content/components/empty_watchlist.dart
> +          size: 0.3.sw,
discussed in DM

2021-08-31 09:21 UTC, VovaMedvediev commented on lib/service/services/signal_r/service/signal_r_service.dart
> +  KeyValueModel _serializeKeys(KeyValueModel keyValue) {
refactored

2021-08-31 15:05 UTC, merged