Signalr service
MyJetWallet/Flutter.JetWallet pull request #13
Opened 2021-05-14 15:16 UTC by VovaMedvediev

2021-05-17 06:27 UTC, eli1stark requested changes

2021-05-17 06:27 UTC, eli1stark commented on lib/service/services/signal_r/service/dto/wallet/assets_response_dto.dart
> +  List<AssetDto> assets;
Use the final keyword for class' parameters to make them immutable

2021-05-17 06:27 UTC, eli1stark commented on lib/service/services/signal_r/service/dto/wallet/assets_response_dto.dart
> +  int now;
Use the final keyword for class' parameters to make them immutable

2021-05-17 06:27 UTC, eli1stark commented on lib/service/services/signal_r/service/dto/wallet/assets_response_dto.dart
> +  String symbol;
final

2021-05-17 06:27 UTC, eli1stark commented on lib/service/services/signal_r/service/dto/wallet/assets_response_dto.dart
> +  String description;
final

2021-05-17 06:27 UTC, eli1stark commented on lib/service/services/signal_r/service/dto/wallet/assets_response_dto.dart
> +  num accuracy;
final, and use `int` or `double` instead of `num`

2021-05-17 06:27 UTC, eli1stark commented on lib/service/services/signal_r/service/dto/wallet/balances_response_dto.dart
> +  num sequenceId;
make parameters final and use `int` or `double` instead of `num`. Fix all occurrences above

2021-05-17 06:27 UTC, eli1stark commented on lib/service/services/signal_r/service/model/wallet/asset_model.dart
> +    required num accuracy,
use `int` or `double` instead of `num`

2021-05-17 06:27 UTC, eli1stark commented on lib/service/services/signal_r/service/model/wallet/balance_model.dart
> +    required num balance,
use `int` or `double` instead of `num`

2021-05-17 06:27 UTC, eli1stark commented on lib/service/services/signal_r/service/model/wallet/balance_model.dart
> +    required num reserve,
use `int` or `double` instead of `num`

2021-05-17 06:27 UTC, eli1stark commented on lib/service/services/signal_r/service/model/wallet/balance_model.dart
> +    required num sequenceId,
use `int` or `double` instead of `num`

2021-05-17 06:27 UTC, eli1stark commented on lib/service/services/signal_r/service/signal_r_service.dart
> +  late HubConnection _hubConnection;
consider using inline initialization like so:
```dart
var _hubConnection = HubConnectionBuilder().withUrl(
    urlSignalR,
).build();
```

2021-05-20 10:55 UTC, VovaMedvediev commented on lib/service/services/signal_r/service/dto/wallet/assets_response_dto.dart
> +  List<AssetDto> assets;
fixed

2021-05-20 10:55 UTC, VovaMedvediev commented on lib/service/services/signal_r/service/dto/wallet/assets_response_dto.dart
> +  int now;
fixed

2021-05-20 10:55 UTC, VovaMedvediev commented on lib/service/services/signal_r/service/dto/wallet/assets_response_dto.dart
> +  String symbol;
fixed

2021-05-20 10:55 UTC, VovaMedvediev commented on lib/service/services/signal_r/service/dto/wallet/assets_response_dto.dart
> +  String description;
fixed

2021-05-20 10:55 UTC, VovaMedvediev commented on lib/service/services/signal_r/service/dto/wallet/assets_response_dto.dart
> +  num accuracy;
fixed

2021-05-20 10:55 UTC, VovaMedvediev commented on lib/service/services/signal_r/service/model/wallet/asset_model.dart
> +    required num accuracy,
fixed

2021-05-20 10:55 UTC, VovaMedvediev commented on lib/service/services/signal_r/service/model/wallet/balance_model.dart
> +    required num balance,
fixed

2021-05-20 10:55 UTC, VovaMedvediev commented on lib/service/services/signal_r/service/model/wallet/balance_model.dart
> +    required num reserve,
fixed

2021-05-20 10:55 UTC, VovaMedvediev commented on lib/service/services/signal_r/service/model/wallet/balance_model.dart
> +    required num sequenceId,
fixed

2021-05-20 10:56 UTC, VovaMedvediev commented on lib/service/services/signal_r/service/signal_r_service.dart
> +  late HubConnection _hubConnection;
such initialization is needed for having the possibility to use _hubConnection in disconnect() method.

2021-05-20 11:04 UTC, merged