SPUI-347 > Add price formatting
MyJetWallet/Flutter.JetWallet pull request #164
Opened 2021-09-22 01:22 UTC by VovaMedvediev

2021-09-22 09:56 UTC, eli1stark requested changes
Needs the second review after changes

2021-09-22 09:56 UTC, eli1stark commented on lib/app/shared/helpers/format_asset_price_value.dart
> +String formatPriceValue({
have questions (in grooming)

2021-09-22 09:56 UTC, eli1stark commented on lib/app/shared/models/currency_model.dart
> +    required String baseCurrencySymbol,
We have BaseCurrencyModel, mixing different structures

2021-09-22 09:56 UTC, eli1stark commented on lib/app/shared/models/currency_model.dart
> +    required int baseCurrencyAccuracy,
We have BaseCurrencyModel, mixing different structures

2021-09-22 09:56 UTC, eli1stark commented on lib/app/screens/market/model/market_item_model.dart
> +    required String baseCurrencySymbol,
We have BaseCurrencyModel, mixing different structures

2021-09-22 09:56 UTC, eli1stark commented on lib/app/screens/market/model/market_item_model.dart
> +    required int baseCurrencyAccuracy,
We have BaseCurrencyModel, mixing different structures

2021-09-23 21:01 UTC, VovaMedvediev commented on lib/app/shared/helpers/format_asset_price_value.dart
> +String formatPriceValue({
refactored

2021-09-23 21:02 UTC, VovaMedvediev commented on lib/app/shared/models/currency_model.dart
> +    required String baseCurrencySymbol,
refactored

2021-09-23 21:02 UTC, VovaMedvediev commented on lib/app/shared/models/currency_model.dart
> +    required int baseCurrencyAccuracy,
refactored

2021-09-23 21:02 UTC, VovaMedvediev commented on lib/app/screens/market/model/market_item_model.dart
> +    required String baseCurrencySymbol,
refactored

2021-09-23 21:02 UTC, VovaMedvediev commented on lib/app/screens/market/model/market_item_model.dart
> +    required int baseCurrencyAccuracy,
refactored

2021-09-24 09:30 UTC, eli1stark requested changes
The ideal function should look like this:
```dart
String formatPriceValue1({
  String? prefix,
  required num value,
  required String symbol,
  required int accuracy,
}) {
  final absValue = value.abs().toStringAsFixed(accuracy);

  if (value.isNegative) {
    if (prefix == null) {
      return '-$absValue$symbol';
    } else {
      return '-$prefix$absValue';
    }
  } else {
    if (prefix == null) {
      return '$absValue$symbol';
    } else {
      return '$prefix$absValue';
    }
  }
}
```
This function should handle cases where `0.00` must look like this `0`. Right now this function doesn't handle this

2021-09-24 09:30 UTC, eli1stark commented on lib/app/shared/helpers/format_asset_price_value.dart
> +  int? accuracy,
all parameters should be required, and only prefix can be null

2021-09-24 09:30 UTC, eli1stark commented on lib/app/shared/helpers/format_asset_price_value.dart
> +    final validatedAccuracy = accuracy ?? 2;
You don't need this if params are required

2021-09-24 09:30 UTC, eli1stark commented on lib/app/shared/helpers/format_asset_price_value.dart
> +    var formattedSymbol = '';
You don't need this if params are required

2021-09-24 09:30 UTC, eli1stark commented on lib/app/shared/helpers/format_asset_price_value.dart
> +    return '${prefix ?? ''}$value$formattedSymbol';
inconsistency in the function.
why in the negative is absValue in the positive just value? why the symbol is different?
they should behave the same

2021-09-24 09:30 UTC, eli1stark commented on lib/app/shared/helpers/format_asset_price_value.dart
> +  return '';
the function can't return an empty string

2021-09-24 09:37 UTC, eli1stark commented on lib/app/shared/providers/currencies_pod/currencies_pod.dart
> +          prefixSymbol: asset.prefixSymbol ?? '',
`prefixSymbol` must be null, if it's an empty string it breaks your function

2021-09-24 09:39 UTC, eli1stark requested changes

2021-09-24 09:39 UTC, eli1stark commented on lib/app/screens/market/model/market_item_model.dart
> +    required String prefixSymbol,
`prefixSymbol` must be null because it breaks your function

2021-09-24 09:44 UTC, eli1stark commented
![Screenshot_1632476613](https://user-images.githubusercontent.com/57593530/134654469-744ee408-868c-4c19-837e-61bd5a255c15.png)
Instead of €0

2021-09-30 16:05 UTC, VovaMedvediev commented on lib/app/shared/helpers/format_asset_price_value.dart
> +  int? accuracy,
fixed

2021-09-30 16:05 UTC, VovaMedvediev commented on lib/app/shared/helpers/format_asset_price_value.dart
> +    final validatedAccuracy = accuracy ?? 2;
+

2021-09-30 16:05 UTC, VovaMedvediev commented on lib/app/shared/helpers/format_asset_price_value.dart
> +    var formattedSymbol = '';
+

2021-09-30 16:05 UTC, VovaMedvediev commented on lib/app/shared/helpers/format_asset_price_value.dart
> +    return '${prefix ?? ''}$value$formattedSymbol';
fixed

2021-09-30 16:05 UTC, VovaMedvediev commented on lib/app/shared/helpers/format_asset_price_value.dart
> +  return '';
fixed

2021-09-30 16:05 UTC, VovaMedvediev commented on lib/app/shared/providers/currencies_pod/currencies_pod.dart
> +          prefixSymbol: asset.prefixSymbol ?? '',
fixed

2021-09-30 16:05 UTC, VovaMedvediev commented on lib/app/screens/market/model/market_item_model.dart
> +    required String prefixSymbol,
fixed

2021-09-30 16:12 UTC, eli1stark approved these changes

2021-09-30 16:13 UTC, merged