SPUI-415 > Bug/operation history details fix
MyJetWallet/Flutter.JetWallet pull request #165
Opened 2021-09-22 01:23 UTC by VovaMedvediev

2021-09-22 09:12 UTC, eli1stark requested changes

2021-09-22 09:12 UTC, eli1stark commented on lib/app/shared/features/wallet/view/components/wallets_body/components/transactions_list_item/components/transaction_details/buy_sell_details.dart
> +              text: '${transactionListItem.swapInfo!.baseRate} '
definitely function

2021-09-22 09:12 UTC, eli1stark commented on lib/app/shared/features/wallet/view/components/wallets_body/components/transactions_list_item/components/transaction_details/buy_sell_details.dart
> +                    '${transactionListItem.swapInfo!.baseRate}'
the same

2021-09-23 08:06 UTC, VovaMedvediev commented on lib/app/shared/features/wallet/view/components/wallets_body/components/transactions_list_item/components/transaction_details/buy_sell_details.dart
> +              text: '${transactionListItem.swapInfo!.baseRate} '
done

2021-09-23 08:06 UTC, VovaMedvediev commented on lib/app/shared/features/wallet/view/components/wallets_body/components/transactions_list_item/components/transaction_details/buy_sell_details.dart
> +                    '${transactionListItem.swapInfo!.baseRate}'
done

2021-09-23 08:13 UTC, eli1stark approved these changes

2021-09-23 08:23 UTC, merged