SPUI-326 > Fix news pagination
MyJetWallet/Flutter.JetWallet pull request #166
Opened 2021-09-22 01:24 UTC by VovaMedvediev

2021-09-22 09:10 UTC, eli1stark requested changes

2021-09-22 09:10 UTC, eli1stark commented on lib/app/shared/features/market_details/view/components/news_block/components/news_item.dart
> +                  DateTime.parse('${item.timestamp}Z').toLocal(),
function?

2021-09-23 08:11 UTC, VovaMedvediev commented on lib/app/shared/features/market_details/view/components/news_block/components/news_item.dart
> +                  DateTime.parse('${item.timestamp}Z').toLocal(),
refactored

2021-09-23 08:14 UTC, eli1stark approved these changes

2021-09-23 08:33 UTC, merged