SPUI-319 > Hide null or empty market details items
MyJetWallet/Flutter.JetWallet pull request #167
Opened 2021-09-22 01:24 UTC by VovaMedvediev

2021-09-22 08:55 UTC, eli1stark requested changes

2021-09-22 08:55 UTC, eli1stark commented on lib/app/shared/features/market_details/view/components/about_block/components/about_block_text.dart
> +        if (marketInfo.whitepaperUrl != null &&
let's refactor to the function

2021-09-23 08:16 UTC, VovaMedvediev commented on lib/app/shared/features/market_details/view/components/about_block/components/about_block_text.dart
> +        if (marketInfo.whitepaperUrl != null &&
done

2021-09-23 08:18 UTC, eli1stark approved these changes

2021-09-23 08:33 UTC, merged