SPUI-493/496 > Add UI for Sign In
MyJetWallet/Flutter.JetWallet pull request #212
Opened 2021-10-28 08:07 UTC by VovaMedvediev

2021-10-30 16:18 UTC, eli1stark requested changes

2021-10-30 16:18 UTC, eli1stark commented on plugins/simple_kit/lib/src/agreements/simple_privacy_policy/simple_policy_text.dart
> +        const SpaceH34(),
No changes to simple_kit outside of ui_guides

2021-11-01 11:42 UTC, VovaMedvediev commented on lib/auth/screens/login/login.dart
> +                        color: Colors.grey[200],
done

2021-11-01 11:42 UTC, VovaMedvediev commented on lib/auth/screens/login/login.dart
> +                        color: Colors.grey[200],
done

2021-11-01 11:51 UTC, VovaMedvediev commented on lib/auth/screens/login/login.dart
> +                        padding: EdgeInsets.symmetric(horizontal: 24.w),
done

2021-11-01 11:51 UTC, VovaMedvediev commented on lib/auth/screens/login/login.dart
> +                        padding: EdgeInsets.symmetric(horizontal: 24.w),
done

2021-11-01 11:51 UTC, VovaMedvediev commented on lib/auth/screens/login/login.dart
> +                          padding: EdgeInsets.symmetric(horizontal: 24.w),
done

2021-11-01 11:52 UTC, VovaMedvediev commented on lib/auth/screens/login/login.dart
> +                        color: Colors.grey[200],
done

2021-11-01 11:52 UTC, VovaMedvediev commented on lib/auth/screens/login/login.dart
> +          padding: EdgeInsets.symmetric(horizontal: 24.w),
done

2021-11-01 11:52 UTC, VovaMedvediev commented on lib/auth/screens/login/login.dart
> +                          padding: EdgeInsets.symmetric(horizontal: 24.w),
done

2021-11-01 11:52 UTC, VovaMedvediev commented on lib/auth/screens/login/login.dart
> +            onBackButtonTap: () => Navigator.of(context).pop(),
done

2021-11-01 11:55 UTC, VovaMedvediev commented on plugins/simple_kit/lib/src/agreements/simple_privacy_policy/simple_policy_text.dart
> +        const SpaceH34(),
done

2021-11-04 09:36 UTC, merged