SPUI-497/489/488 - Sign up flow
MyJetWallet/Flutter.JetWallet pull request #218
Opened 2021-11-04 09:12 UTC by VovaMedvediev

2021-11-04 09:42 UTC, eli1stark requested changes

2021-11-04 09:42 UTC, eli1stark commented on lib/auth/screens/login/login.dart
> +              color: SColorsLight().grey5,
use sColorPod

2021-11-04 09:42 UTC, eli1stark commented on lib/auth/screens/login/login.dart
> +                          color: SColorsLight().white,
sColorsPod

2021-11-04 09:42 UTC, eli1stark commented on lib/auth/screens/register/components/register_password_screen.dart
> +                color: Colors.grey[200],
sColorsPod

2021-11-04 09:42 UTC, eli1stark commented on lib/auth/screens/register/components/register_password_screen.dart
> +                      padding: EdgeInsets.symmetric(horizontal: 24.w),
use SPaddingH24

2021-11-04 09:42 UTC, eli1stark commented on lib/auth/screens/register/components/register_password_screen.dart
> +                      color: Colors.white,
sColorsPod

2021-11-04 09:42 UTC, eli1stark commented on lib/auth/screens/register/components/register_password_screen.dart
> +                      padding: EdgeInsets.symmetric(horizontal: 24.w),
use SPaddingH24

2021-11-04 09:42 UTC, eli1stark commented on lib/auth/screens/register/components/register_password_screen.dart
> +                      padding: EdgeInsets.symmetric(horizontal: 24.w),
use SPaddingH24

2021-11-04 09:42 UTC, eli1stark commented on lib/auth/screens/register/components/register_password_screen.dart
> +                      color: Colors.grey[200],
sColorsPod

2021-11-04 09:42 UTC, eli1stark commented on lib/auth/screens/register/register.dart
> +        padding: EdgeInsets.symmetric(horizontal: 24.w),
SPageFrameWithPadding

2021-11-04 09:42 UTC, eli1stark commented
not finished

2021-11-04 09:46 UTC, eli1stark requested changes

2021-11-04 09:46 UTC, eli1stark commented on lib/auth/screens/register/register.dart
> +            color: Colors.grey[200],
sColorsPod

2021-11-04 09:46 UTC, eli1stark commented on lib/auth/screens/register/register.dart
> +                  padding: EdgeInsets.symmetric(horizontal: 24.w),
SPaddingH24

2021-11-04 09:46 UTC, eli1stark commented on lib/auth/screens/register/register.dart
> +                  color: Colors.grey[200],
sColorsPod

2021-11-04 09:46 UTC, eli1stark commented on lib/auth/screens/register/register.dart
> +                    padding: EdgeInsets.symmetric(horizontal: 24.w),
SPaddingH24

2021-11-04 09:46 UTC, eli1stark commented on lib/auth/screens/register/register.dart
> +                  padding: EdgeInsets.symmetric(horizontal: 24.w),
SPaddingH24

2021-11-04 09:46 UTC, eli1stark commented on lib/auth/screens/register/register.dart
> +                  color: Colors.grey[200],
sColorsPod

2021-11-04 09:46 UTC, eli1stark commented on lib/auth/shared/components/password_validation/password_validation.dart
> +          color: Colors.grey[200],
sColorsPod

2021-11-04 09:46 UTC, eli1stark commented on lib/auth/screens/register/register.dart
> +                Container(
repeated widget 1

2021-11-04 09:46 UTC, eli1stark commented on lib/auth/shared/components/password_validation/password_validation.dart
> +        Container(
repeated widget 1

2021-11-04 09:46 UTC, eli1stark commented on lib/auth/screens/register/components/register_password_screen.dart
> +                    Container(
repeated widget 1

2021-11-04 09:49 UTC, eli1stark requested changes

2021-11-04 09:49 UTC, eli1stark commented on lib/auth/screens/register/components/register_password_screen.dart
> +        child: SPageFrame(
SPageFrameWithPadding

2021-11-04 09:49 UTC, eli1stark commented on lib/auth/shared/notifiers/credentials_notifier/credentials_notifier.dart
> +  bool get emailIsNotEmptyAndPolicyChecked {
we need to check email using regex

2021-11-04 09:49 UTC, eli1stark commented on lib/auth/screens/register/components/register_password_screen.dart
> +  void _showErrorNotification(SNotificationQueueNotifier notifier) {
repeated logic 2

2021-11-04 09:49 UTC, eli1stark commented on lib/auth/screens/register/register.dart
> +  void _showErrorNotification(SNotificationQueueNotifier notifier) {
repeated logic 2

2021-11-05 05:54 UTC, VovaMedvediev commented on lib/auth/screens/login/login.dart
> +              color: SColorsLight().grey5,
done

2021-11-05 05:54 UTC, VovaMedvediev commented on lib/auth/screens/login/login.dart
> +                          color: SColorsLight().white,
done

2021-11-05 05:54 UTC, VovaMedvediev commented on lib/auth/screens/register/components/register_password_screen.dart
> +                color: Colors.grey[200],
done

2021-11-05 05:55 UTC, VovaMedvediev commented on lib/auth/screens/register/components/register_password_screen.dart
> +                      padding: EdgeInsets.symmetric(horizontal: 24.w),
done

2021-11-05 05:55 UTC, VovaMedvediev commented on lib/auth/screens/register/components/register_password_screen.dart
> +                      color: Colors.white,
done

2021-11-05 05:56 UTC, VovaMedvediev commented on lib/auth/screens/register/components/register_password_screen.dart
> +                      padding: EdgeInsets.symmetric(horizontal: 24.w),
done

2021-11-05 05:56 UTC, VovaMedvediev commented on lib/auth/screens/register/components/register_password_screen.dart
> +                      padding: EdgeInsets.symmetric(horizontal: 24.w),
done

2021-11-05 05:56 UTC, VovaMedvediev commented on lib/auth/screens/register/components/register_password_screen.dart
> +                      color: Colors.grey[200],
done

2021-11-05 05:57 UTC, VovaMedvediev commented on lib/auth/screens/register/register.dart
> +        padding: EdgeInsets.symmetric(horizontal: 24.w),
done

2021-11-05 05:58 UTC, VovaMedvediev commented on lib/auth/screens/register/register.dart
> +            color: Colors.grey[200],
done

2021-11-05 05:58 UTC, VovaMedvediev commented on lib/auth/screens/register/register.dart
> +                  padding: EdgeInsets.symmetric(horizontal: 24.w),
done

2021-11-05 05:59 UTC, VovaMedvediev commented on lib/auth/screens/register/register.dart
> +                  color: Colors.grey[200],
done

2021-11-05 05:59 UTC, VovaMedvediev commented on lib/auth/screens/register/register.dart
> +                    padding: EdgeInsets.symmetric(horizontal: 24.w),
done

2021-11-05 05:59 UTC, VovaMedvediev commented on lib/auth/screens/register/register.dart
> +                  padding: EdgeInsets.symmetric(horizontal: 24.w),
done

2021-11-05 05:59 UTC, VovaMedvediev commented on lib/auth/screens/register/register.dart
> +                  color: Colors.grey[200],
done

2021-11-05 05:59 UTC, VovaMedvediev commented on lib/auth/shared/components/password_validation/password_validation.dart
> +          color: Colors.grey[200],
done

2021-11-05 08:00 UTC, VovaMedvediev commented on lib/auth/screens/register/register.dart
> +                Container(
done

2021-11-05 08:00 UTC, VovaMedvediev commented on lib/auth/shared/components/password_validation/password_validation.dart
> +        Container(
done

2021-11-05 08:01 UTC, VovaMedvediev commented on lib/auth/screens/register/components/register_password_screen.dart
> +                    Container(
done

2021-11-05 08:01 UTC, VovaMedvediev commented on lib/auth/screens/register/components/register_password_screen.dart
> +        child: SPageFrame(
done

2021-11-05 08:02 UTC, VovaMedvediev commented on lib/auth/shared/notifiers/credentials_notifier/credentials_notifier.dart
> +  bool get emailIsNotEmptyAndPolicyChecked {
no, we are able to input any not-empty email. If the email is wrong the user will see error notification

2021-11-05 08:03 UTC, VovaMedvediev commented on lib/auth/screens/register/components/register_password_screen.dart
> +  void _showErrorNotification(SNotificationQueueNotifier notifier) {
done

2021-11-05 08:10 UTC, VovaMedvediev commented on lib/auth/screens/register/register.dart
> +  void _showErrorNotification(SNotificationQueueNotifier notifier) {
done

2021-11-05 08:29 UTC, eli1stark requested changes

2021-11-05 08:29 UTC, eli1stark commented on lib/auth/shared/components/password_validation/password_validation.dart
> +        const Grey24HPadding(),
Rename to GreyPaddingH24 to our app standards

2021-11-05 08:35 UTC, VovaMedvediev commented on lib/auth/shared/components/password_validation/password_validation.dart
> +        const Grey24HPadding(),
components is deleted

2021-11-05 08:44 UTC, merged