Sp UI 569/security screen
MyJetWallet/Flutter.JetWallet pull request #239
Opened 2021-11-14 04:10 UTC by DenisMartych

2021-11-20 09:05 UTC, eli1stark requested changes

2021-11-20 09:05 UTC, eli1stark commented on lib/shared/notifiers/phone_number_notifier/phone_number_state.dart
> +    @Default('') String? asset,
redundant nullable, remove all occurrences

2021-11-20 09:05 UTC, eli1stark commented on plugins/simple_kit/lib/src/colors/view/simple_colors_light.dart
> +  Color grey6 = const Color(0xFFE0EBFA);
investigate

2021-11-21 09:30 UTC, DenisMartych commented on plugins/simple_kit/lib/src/colors/view/simple_colors_light.dart
> +  Color grey6 = const Color(0xFFE0EBFA);
remove colors6

2021-11-22 08:29 UTC, DenisMartych commented on lib/shared/notifiers/enter_phone_notifier/enter_phone_state.dart
> +    @Default('+380') String? isoCode,
done

2021-11-22 08:29 UTC, DenisMartych commented on lib/shared/notifiers/phone_number_notifier/phone_number_notifier.dart
> +    if (state.phoneNumber != '' &&
done

2021-11-22 08:29 UTC, DenisMartych commented on lib/shared/notifiers/phone_number_notifier/phone_number_state.dart
> +    @Default('') String? asset,
done

2021-11-22 08:30 UTC, DenisMartych commented on plugins/simple_kit/lib/src/colors/view/simple_colors_light.dart
> +  Color grey6 = const Color(0xFFE0EBFA);
remove grey6

2021-11-22 09:25 UTC, merged