SPUI-708: Change phone number
MyJetWallet/Flutter.JetWallet pull request #263
Opened 2021-11-25 11:37 UTC by DenisMartych

2021-11-26 10:05 UTC, eli1stark requested changes

2021-11-26 10:05 UTC, eli1stark commented on lib/shared/features/phone_verification/phone_verification_confirm/view/change_phone_verification_confirm.dart
> +          if (phone.union is Loading) const ScaffoldLoader(),
change to SPageFrame loading

2021-11-26 12:49 UTC, eli1stark requested changes

2021-11-26 12:49 UTC, eli1stark commented on lib/app/shared/features/profile_details/notifier/change_phone_notifier/change_phone_notifier.dart
> +    required this.read,
in this specific case, you can do this without a named parameter, this way it looks cleaner.
`ChangePhoneNotifier(this.read)...`

2021-11-26 12:49 UTC, eli1stark commented on lib/app/shared/features/profile_details/view/components/change_phone_number/change_phone_number.dart
> +    final statePhoneNumber = useProvider(phoneNumberNotipod);
phoneNumber

2021-11-26 12:49 UTC, eli1stark commented on lib/app/shared/features/profile_details/view/components/change_phone_number/change_phone_number.dart
> +    final notifierPhoneNumber = useProvider(phoneNumberNotipod.notifier);
phoneNumberN

2021-11-26 12:49 UTC, eli1stark commented on lib/app/shared/features/profile_details/view/profile_details.dart
> +
remove space

2021-11-26 12:49 UTC, eli1stark commented on lib/app/shared/features/profile_details/view/profile_details.dart
> +    final changePhone = useProvider(changePhoneNotipod);
changePhoneN

2021-11-26 12:49 UTC, eli1stark commented on lib/shared/features/phone_verification/phone_verification_confirm/view/phone_verification_confirm.dart
> +  final bool isChangeFonAlert;
Fon?

2021-11-26 12:49 UTC, eli1stark commented on lib/shared/features/phone_verification/phone_verification_confirm/view/phone_verification_confirm.dart
> +    Function() onVerified, {
use named here

2021-11-26 12:49 UTC, eli1stark commented on lib/shared/features/phone_verification/phone_verification_confirm/view/phone_verification_confirm.dart
> +    BuildContext context,
use named here

2021-11-26 12:49 UTC, eli1stark commented on lib/shared/notifiers/user_info_notifier/user_info_notifier.dart
> +  void updatePhoneNumber(String phone) {
remove

2021-11-26 12:49 UTC, eli1stark commented on lib/shared/notifiers/user_info_notifier/user_info_state.dart
> +  bool get enableChangePhoneNumber => phone.isNotEmpty;
reaname to isPhoneNumberActive

2021-11-26 12:53 UTC, DenisMartych commented on lib/app/shared/features/profile_details/notifier/change_phone_notifier/change_phone_notifier.dart
> +    required this.read,
done

2021-11-26 12:54 UTC, DenisMartych commented on lib/app/shared/features/profile_details/view/components/change_phone_number/change_phone_number.dart
> +    final statePhoneNumber = useProvider(phoneNumberNotipod);
done

2021-11-26 12:54 UTC, DenisMartych commented on lib/app/shared/features/profile_details/view/components/change_phone_number/change_phone_number.dart
> +    final notifierPhoneNumber = useProvider(phoneNumberNotipod.notifier);
done

2021-11-26 12:55 UTC, DenisMartych commented on lib/app/shared/features/profile_details/view/profile_details.dart
> +
done

2021-11-26 12:55 UTC, DenisMartych commented on lib/app/shared/features/profile_details/view/profile_details.dart
> +    final changePhone = useProvider(changePhoneNotipod);
not used, remove

2021-11-26 13:00 UTC, DenisMartych commented on lib/shared/notifiers/user_info_notifier/user_info_notifier.dart
> +  void updatePhoneNumber(String phone) {
remove

2021-11-28 20:50 UTC, DenisMartych commented on lib/shared/features/phone_verification/phone_verification_confirm/view/change_phone_verification_confirm.dart
> +          if (phone.union is Loading) const ScaffoldLoader(),
done

2021-11-28 21:10 UTC, DenisMartych commented on lib/shared/features/phone_verification/phone_verification_confirm/view/phone_verification_confirm.dart
> +    BuildContext context,
done

2021-11-28 21:13 UTC, DenisMartych commented on lib/shared/notifiers/user_info_notifier/user_info_state.dart
> +  bool get enableChangePhoneNumber => phone.isNotEmpty;
done

2021-11-29 09:15 UTC, eli1stark requested changes

2021-11-29 09:15 UTC, eli1stark commented on lib/app/shared/features/profile_details/view/components/change_password/change_password.dart
> +          },
remove additional line

2021-11-29 09:36 UTC, DenisMartych commented on lib/app/shared/features/profile_details/view/components/change_password/change_password.dart
> +          },
done

2021-11-29 09:37 UTC, DenisMartych commented on lib/shared/features/phone_verification/phone_verification_confirm/view/phone_verification_confirm.dart
> +          //if (phone.union is Loading) const ScaffoldLoader(),
done

2021-11-29 09:39 UTC, merged