Market detail UI
MyJetWallet/Flutter.JetWallet pull request #297
Opened 2021-12-09 09:13 UTC by VovaMedvediev

2021-12-09 09:51 UTC, eli1stark commented on plugins/simple_chart/lib/components/dashed_divider/dashed_divider.dart
> +                        color: Color(0xFFE0E5EB),
??

2021-12-13 09:12 UTC, VovaMedvediev commented on plugins/simple_chart/lib/components/dashed_divider/dashed_divider.dart
> +                        color: Color(0xFFE0E5EB),
done

2021-12-13 09:29 UTC, eli1stark requested changes

2021-12-13 09:29 UTC, eli1stark commented on lib/app/screens/news/news.dart
> +                      height: 110.h,
remove

2021-12-13 09:29 UTC, eli1stark commented on lib/app/screens/news/news.dart
> +                        vertical: 20.h,
remove

2021-12-13 09:29 UTC, eli1stark commented on lib/app/shared/features/chart/view/asset_chart.dart
> +            chartHeight: 240.h,
remove

2021-12-13 09:29 UTC, eli1stark commented on lib/app/shared/features/chart/view/asset_chart.dart
> +            chartWidgetHeight: 336.h,
remove

2021-12-13 09:29 UTC, eli1stark commented on lib/app/shared/features/chart/view/asset_chart.dart
> +            chartHeight: 240.h,
remove

2021-12-13 09:29 UTC, eli1stark commented on lib/app/shared/features/chart/view/asset_chart.dart
> +            chartWidgetHeight: 336.h,
remove

2021-12-13 09:29 UTC, eli1stark commented on lib/app/shared/features/chart/view/asset_chart.dart
> +        chartHeight: 240.h,
remove

2021-12-13 09:29 UTC, eli1stark commented on lib/app/shared/features/chart/view/asset_chart.dart
> +        chartWidgetHeight: 336.h,
remove

2021-12-13 09:29 UTC, eli1stark commented on lib/app/shared/features/market_details/view/components/about_block/components/clickable_underlined_text.dart
> +          bottom: 3.h,
remove

2021-12-13 09:29 UTC, eli1stark commented on lib/app/shared/features/market_details/view/components/about_block/components/clickable_underlined_text.dart
> +              width: 2.h,
remove

2021-12-13 09:29 UTC, eli1stark commented on lib/app/shared/features/market_details/view/components/market_news_block/market_news_block.dart
> +                    bottom: 24.h,
remove

2021-12-13 09:29 UTC, eli1stark commented on lib/app/shared/features/market_details/view/market_details.dart
> +          onBackButtonTap: () => Navigator.of(context).pop(),
redundant argument. Headers by default use pop if parameter is null

2021-12-13 09:29 UTC, eli1stark commented on plugins/simple_chart/lib/components/dashed_divider/dashed_divider.dart
> +      padding: EdgeInsets.only(left: 24.w),
remove

2021-12-13 09:29 UTC, eli1stark commented on plugins/simple_chart/lib/components/dashed_divider/dashed_divider.dart
> +          final dashWidth = 5.w;
remove

2021-12-13 09:29 UTC, eli1stark commented on plugins/simple_chart/lib/components/dashed_divider/dashed_divider.dart
> +                    height: 1.h,
remove

2021-12-13 09:29 UTC, eli1stark commented on plugins/simple_chart/lib/renderer/chart_painter.dart
> +      final x = 24.w;
remove

2021-12-13 09:29 UTC, eli1stark commented on plugins/simple_chart/lib/renderer/chart_painter.dart
>        var y = getMainY(mMainLowMinValue!) + 20.h;
remove

2021-12-13 09:36 UTC, VovaMedvediev commented on plugins/simple_chart/lib/components/dashed_divider/dashed_divider.dart
> +                        color: Color(0xFFE0E5EB),
done

2021-12-13 09:37 UTC, VovaMedvediev commented on lib/app/screens/news/news.dart
> +                      height: 110.h,
done

2021-12-13 09:37 UTC, VovaMedvediev commented on lib/app/screens/news/news.dart
> +                        vertical: 20.h,
done

2021-12-13 09:37 UTC, VovaMedvediev commented on lib/app/shared/features/chart/view/asset_chart.dart
> +            chartHeight: 240.h,
done

2021-12-13 09:37 UTC, VovaMedvediev commented on lib/app/shared/features/chart/view/asset_chart.dart
> +            chartWidgetHeight: 336.h,
+

2021-12-13 09:38 UTC, VovaMedvediev commented on lib/app/shared/features/chart/view/asset_chart.dart
> +            chartWidgetHeight: 336.h,
+

2021-12-13 09:38 UTC, VovaMedvediev commented on lib/app/shared/features/chart/view/asset_chart.dart
> +            chartWidgetHeight: 336.h,
done

2021-12-13 09:38 UTC, VovaMedvediev commented on lib/app/shared/features/chart/view/asset_chart.dart
> +            chartHeight: 240.h,
done

2021-12-13 09:38 UTC, VovaMedvediev commented on lib/app/shared/features/chart/view/asset_chart.dart
> +            chartWidgetHeight: 336.h,
done

2021-12-13 09:38 UTC, VovaMedvediev commented on lib/app/shared/features/chart/view/asset_chart.dart
> +        chartHeight: 240.h,
done

2021-12-13 09:38 UTC, VovaMedvediev commented on lib/app/shared/features/chart/view/asset_chart.dart
> +        chartWidgetHeight: 336.h,
done

2021-12-13 09:39 UTC, VovaMedvediev commented on lib/app/shared/features/market_details/view/components/about_block/components/clickable_underlined_text.dart
> +          bottom: 3.h,
done

2021-12-13 09:39 UTC, VovaMedvediev commented on lib/app/shared/features/market_details/view/components/about_block/components/clickable_underlined_text.dart
> +              width: 2.h,
done

2021-12-13 09:39 UTC, VovaMedvediev commented on lib/app/shared/features/market_details/view/components/market_news_block/market_news_block.dart
> +                    bottom: 24.h,
done

2021-12-13 09:39 UTC, VovaMedvediev commented on lib/app/shared/features/market_details/view/market_details.dart
> +          onBackButtonTap: () => Navigator.of(context).pop(),
done

2021-12-13 09:41 UTC, VovaMedvediev commented on plugins/simple_chart/lib/components/dashed_divider/dashed_divider.dart
> +      padding: EdgeInsets.only(left: 24.w),
done

2021-12-13 09:41 UTC, VovaMedvediev commented on plugins/simple_chart/lib/components/dashed_divider/dashed_divider.dart
> +          final dashWidth = 5.w;
done

2021-12-13 09:41 UTC, VovaMedvediev commented on plugins/simple_chart/lib/components/dashed_divider/dashed_divider.dart
> +                    height: 1.h,
done

2021-12-13 09:41 UTC, VovaMedvediev commented on plugins/simple_chart/lib/renderer/chart_painter.dart
> +      final x = 24.w;
done

2021-12-13 09:42 UTC, VovaMedvediev commented on plugins/simple_chart/lib/renderer/chart_painter.dart
>        var y = getMainY(mMainLowMinValue!) + 20.h;
done

2021-12-13 10:39 UTC, merged