Feature/sp UI 91
MyJetWallet/Flutter.JetWallet pull request #30
Opened 2021-05-28 16:06 UTC by VovaMedvediev

2021-05-31 07:41 UTC, eli1stark requested changes
Waiting for the update! If you will have some questions don't hesitate to ask

2021-05-31 07:41 UTC, eli1stark commented on .gitignore
> -**/ios/Flutter/.last_build_id
Remove this line from `Flutter/Dart/Pub related section`
It makes sense to leave it in the `iOS/XCode related section`

2021-05-31 07:41 UTC, eli1stark commented on lib/app/screens/chart/notifiers/chart_notifier.dart
> +extension on DateTime {
Consider creating function over extension.

2021-05-31 07:41 UTC, eli1stark commented on lib/app/screens/chart/notifiers/chart_notifier.dart
> +        DataFeedUtil.calculateHistoryDepth(resolution);
Consider using trailing comma when you are shifted to the next line
From:
```dart
final calculatedHistoryDepth = 
     DataFeedUtil.calculateHistoryDepth(resolution);
```
To:
```dart
final calculatedHistoryDepth = DataFeedUtil.calculateHistoryDepth(
    resolution,
);
```

2021-05-31 07:41 UTC, eli1stark commented on lib/app/screens/chart/notifiers/chart_notifier.dart
> +    final calculatedHistoryDepth =
Simplify the name to make it more concise.
From `calculatedHistoryDepth ` 
To: `depth`
I recommend you to read a [short article](http://journal.stuffwithstuff.com/2009/06/05/naming-things-in-code/) on naming from dartlang engineer

2021-05-31 07:41 UTC, eli1stark commented on lib/app/screens/chart/notifiers/chart_notifier.dart
> +  Future<void> getCandles(String resolution, String instrumentId) async {
AVOID starting a method name with `get`.
Why? https://dart.dev/guides/language/effective-dart/design#avoid-starting-a-method-name-with-get

2021-05-31 07:41 UTC, eli1stark commented on lib/app/screens/chart/notifiers/chart_notifier.dart
> +        toDate.subtract(calculatedHistoryDepth.intervalBackDuration);
Consider using trailing comma when you are shifted to the next line.

2021-05-31 07:41 UTC, eli1stark commented on lib/app/screens/chart/notifiers/chart_notifier.dart
> +  void initCandles(List<CandleModel> candles) {
Rename this function to `updateCandles` and reuse it in your Notifier's logic

2021-05-31 07:41 UTC, eli1stark commented on lib/app/screens/chart/notifiers/chart_notifier.dart
> +    state = state.copyWith(candles: candles.candles);
You can use `updateCandles` function I described below.

2021-05-31 07:41 UTC, eli1stark commented on lib/app/screens/chart/notifiers/chart_notifier.dart
> +        isUtc: true);
Use trailing comma:
```dart
  isUtc: true,
);
```

2021-05-31 07:41 UTC, eli1stark commented on lib/app/screens/chart/notifiers/state/charts_state.dart
> +class ChartsState with _$ChartsState {
If you are not planning to extend this state further you can delete it and use just ` List<CandleModel>` without additional abstractions.

2021-05-31 07:41 UTC, eli1stark commented on lib/app/screens/chart/view/components/chart_view.dart
> +                .map((e) => KLineEntity.fromJson(e.toJson()))
It's a very bad practice to use serialization inside the `view` layer. 
All serialization must be done inside the `service` layer.
In exceptional cases, it can be done inside the `state` layer, but I'm not sure if this is the case.

2021-05-31 07:41 UTC, eli1stark commented on lib/app/screens/chart/view/components/chart_view.dart
> +      loading: () {
Consider using `=>` for short callbacks.
From:
```dart
loading: () {       
   return Loader();      
},
```
To:
```dart
loading: () => Loader(); 
```

2021-05-31 07:41 UTC, eli1stark commented on lib/app/screens/chart/view/components/chart_view.dart
> +      error: (_, __) {
The same case as with loading

2021-05-31 07:41 UTC, eli1stark commented on lib/service/services/charts/service/charts_service.dart
> +      ) {
Looks like this line is not formatted properly, make sure to run `dart.fmt`

2021-05-31 07:41 UTC, eli1stark commented on lib/service/services/charts/service/services/get_candles_service.dart
> +    ) async {
Looks like this line is not formatted properly, make sure to run dart.fmt
Make sure that you checked all your files on formatting before committing

2021-05-31 08:46 UTC, VovaMedvediev commented on .gitignore
> -**/ios/Flutter/.last_build_id
moved to iOS/XCode related section

2021-05-31 08:53 UTC, VovaMedvediev commented on lib/app/screens/chart/notifiers/chart_notifier.dart
> +extension on DateTime {
refactored to function

2021-05-31 08:53 UTC, VovaMedvediev commented on lib/app/screens/chart/notifiers/chart_notifier.dart
> +        DataFeedUtil.calculateHistoryDepth(resolution);
refactored

2021-05-31 09:09 UTC, VovaMedvediev commented on lib/app/screens/chart/notifiers/chart_notifier.dart
> +    final calculatedHistoryDepth =
renamed

2021-05-31 09:10 UTC, VovaMedvediev commented on lib/app/screens/chart/notifiers/chart_notifier.dart
> +  Future<void> getCandles(String resolution, String instrumentId) async {
renamed to fetchCandles

2021-05-31 09:11 UTC, VovaMedvediev commented on lib/app/screens/chart/notifiers/chart_notifier.dart
> +        toDate.subtract(calculatedHistoryDepth.intervalBackDuration);
refactored

2021-05-31 09:11 UTC, VovaMedvediev commented on lib/app/screens/chart/notifiers/chart_notifier.dart
> +  void initCandles(List<CandleModel> candles) {
renamed

2021-05-31 09:12 UTC, VovaMedvediev commented on lib/app/screens/chart/notifiers/chart_notifier.dart
> +    state = state.copyWith(candles: candles.candles);
refactored

2021-05-31 09:12 UTC, VovaMedvediev commented on lib/app/screens/chart/notifiers/chart_notifier.dart
> +        isUtc: true);
refactored

2021-05-31 09:22 UTC, VovaMedvediev commented on lib/app/screens/chart/notifiers/state/charts_state.dart
> +class ChartsState with _$ChartsState {
I am planning to extend the state so this abstraction is needed

2021-05-31 13:41 UTC, VovaMedvediev commented on lib/app/screens/chart/view/components/chart_view.dart
> +      error: (_, __) {
fixed

2021-05-31 13:41 UTC, VovaMedvediev commented on lib/app/screens/chart/view/components/chart_view.dart
> +      loading: () {
refactored

2021-05-31 13:43 UTC, VovaMedvediev commented on lib/service/services/charts/service/charts_service.dart
> +      ) {
done

2021-05-31 13:43 UTC, VovaMedvediev commented on lib/service/services/charts/service/services/get_candles_service.dart
> +    ) async {
done

2021-05-31 14:57 UTC, VovaMedvediev commented on lib/app/screens/chart/view/components/chart_view.dart
> +                .map((e) => KLineEntity.fromJson(e.toJson()))
moved to service layer

2021-06-01 07:17 UTC, eli1stark approved these changes

2021-06-01 10:56 UTC, merged