SPUI-722: add referral stats
MyJetWallet/Flutter.JetWallet pull request #301
Opened 2021-12-10 13:24 UTC by DenisMartych

2021-12-10 15:29 UTC, eli1stark requested changes

2021-12-10 15:29 UTC, eli1stark commented on lib/app/shared/features/rewards/helper/reward_description_item.dart
>        width: 287.w,
fix

2021-12-10 15:29 UTC, eli1stark commented on lib/app/shared/features/rewards/helper/set_reward_description_item.dart
> +Widget setRewardDescriptionItem(
rename set to create

2021-12-10 15:29 UTC, eli1stark commented on lib/app/shared/features/rewards/view/rewards.dart
> +    final rng = Random();
use normal name

2021-12-10 15:29 UTC, eli1stark commented on lib/app/shared/features/rewards/view/rewards.dart
> +                  if (item.conditions == null ||
refactor to private function

2021-12-10 15:29 UTC, eli1stark commented on lib/app/shared/features/rewards/view/rewards.dart
> +                  if (item.conditions != null &&
refactor to second private function that you can use in the first one

2021-12-10 15:29 UTC, eli1stark commented on plugins/simple_kit/lib/src/referral_stats/simple_referral_stats_item.dart
> +  final Color? valueColor;
sort

2021-12-10 15:29 UTC, eli1stark commented on plugins/simple_kit/lib/src/referral_stats/simple_referral_stats_item.dart
> +                : sSubtitle3Style,
```dart
sSubtitle3Style.copyWith(
  color: valueColor ?? SColorsLight().black
)
```

2021-12-10 15:41 UTC, DenisMartych commented on lib/app/shared/features/rewards/helper/reward_description_item.dart
>        width: 287.w,
done

2021-12-10 15:42 UTC, DenisMartych commented on lib/app/shared/features/rewards/helper/set_reward_description_item.dart
> +Widget setRewardDescriptionItem(
done

2021-12-10 15:43 UTC, DenisMartych commented on lib/app/shared/features/rewards/view/rewards.dart
> +    final rng = Random();
done

2021-12-10 15:46 UTC, DenisMartych commented on plugins/simple_kit/lib/src/referral_stats/simple_referral_stats_item.dart
> +  final Color? valueColor;
done

2021-12-10 15:47 UTC, DenisMartych commented on plugins/simple_kit/lib/src/referral_stats/simple_referral_stats_item.dart
> +                : sSubtitle3Style,
done

2021-12-10 16:13 UTC, DenisMartych commented on lib/app/shared/features/rewards/view/rewards.dart
> +                  if (item.conditions == null ||
done

2021-12-10 16:13 UTC, DenisMartych commented on lib/app/shared/features/rewards/view/rewards.dart
> +                  if (item.conditions != null &&
done

2021-12-13 09:29 UTC, VovaMedvediev commented on lib/app/shared/features/referral_stats/notifier/campaign_and_referral_notifier.dart
> +      campaigns: <CampaignModel>[],
I think it is necessarily to add type here

2021-12-13 09:29 UTC, VovaMedvediev commented on lib/app/shared/features/referral_stats/notifier/campaign_and_referral_notifier.dart
> +    _logger.log(notifier, 'updateReferrerStats');
function name is not equal to log function name

2021-12-13 09:29 UTC, VovaMedvediev commented on lib/app/shared/features/rewards/helper/create_reward_banner.dart
> +Widget createRewardBanner(
it is not ok to create functions which returns Widget. It is better to add Stateless Widget. https://stackoverflow.com/a/53234826

2021-12-13 09:29 UTC, VovaMedvediev commented on lib/app/shared/features/rewards/helper/create_reward_banner.dart
> +        rng.nextInt(3),
add informative const value. Currently I can't understand what is "3"

2021-12-13 09:29 UTC, VovaMedvediev commented on lib/app/shared/features/rewards/view/rewards.dart
> +      child: Column(
I think Column is redundant here. It has only 1 child

2021-12-13 09:33 UTC, eli1stark commented on lib/app/shared/features/rewards/helper/create_reward_banner.dart
> +Widget createRewardBanner(
agree

2021-12-13 09:57 UTC, DenisMartych commented on lib/app/shared/features/referral_stats/notifier/campaign_and_referral_notifier.dart
> +    _logger.log(notifier, 'updateReferrerStats');
done

2021-12-13 09:57 UTC, DenisMartych commented on lib/app/shared/features/rewards/helper/create_reward_banner.dart
> +Widget createRewardBanner(
done

2021-12-13 09:58 UTC, DenisMartych commented on lib/app/shared/features/rewards/helper/create_reward_banner.dart
> +        rng.nextInt(3),
done

2021-12-13 10:19 UTC, DenisMartych commented on lib/app/shared/features/referral_stats/notifier/campaign_and_referral_notifier.dart
> +      campaigns: <CampaignModel>[],
done

2021-12-13 10:20 UTC, DenisMartych commented on lib/app/shared/features/rewards/view/rewards.dart
> +      child: Column(
done

2021-12-13 11:14 UTC, merged