SPUI-756 > Referral program
MyJetWallet/Flutter.JetWallet pull request #307
Opened 2021-12-14 12:40 UTC by DenisMartych

2021-12-14 22:18 UTC, VovaMedvediev requested changes

2021-12-14 22:18 UTC, VovaMedvediev commented on lib/app/screens/market/view/components/market_banner/market_banner.dart
> +          itemBuilder: (BuildContext context, int index) => GestureDetector(
Ilya says that it is better to use {} for non one-liners. But for me it is ok :)

2021-12-14 22:18 UTC, VovaMedvediev commented on lib/app/screens/market/view/components/market_banner/market_banner.dart
> +    final secondPartOfDeepLink2 = secondPartOfDeepLink.split('&apn')[0];
try to use more informative/understandble name

2021-12-14 22:18 UTC, VovaMedvediev commented on lib/shared/notifiers/user_info_notifier/user_info_state.dart
> +    @Default('') String? referralLink,
default value is ''. For what reason it is nullable?

2021-12-14 22:18 UTC, VovaMedvediev commented on lib/shared/notifiers/user_info_notifier/user_info_state.dart
> +    @Default('') String? referralCode,
same here

2021-12-14 22:18 UTC, VovaMedvediev commented on lib/shared/services/deep_link_service.dart
> +    if (command == _confirmEmail) {
please refactor to switch-case construction

2021-12-14 22:18 UTC, VovaMedvediev commented on lib/shared/services/deep_link_service.dart
> +    this.read,
please refactor to concrete parameters. Currently, it is not obvious that this class has a lot of dependencies, only ref.read

2021-12-14 22:18 UTC, VovaMedvediev commented on plugins/simple_kit/lib/src/referral_invite/simple_referral_invite_body.dart
> +                      onTap: () {},
Add implementation or TODO please

2021-12-14 22:18 UTC, VovaMedvediev commented on plugins/simple_kit/lib/src/referral_invite/simple_referral_invite_body.dart
> +                onTap: () {},
same here

2021-12-14 22:18 UTC, VovaMedvediev commented on plugins/simple_kit/lib/src/referral_invite/simple_referral_invite_body.dart
> +            onTap: () {},
same here

2021-12-15 04:54 UTC, eli1stark reviewed
I haven't reviewed yet, just left one comment

2021-12-15 04:54 UTC, eli1stark commented on lib/shared/services/deep_link_service.dart
> +    this.read,
The whole point of `ref.read` is to avoid redundant dependency injection.
And this is not possible to do this way because objects that Reader is accessing are changing over time and at the moment when it will be accessed it will be outdated

2021-12-15 09:44 UTC, eli1stark requested changes

2021-12-15 09:44 UTC, eli1stark commented on lib/shared/services/deep_link_service.dart
> +    switch (command) {
return to `if` instead of `switch` case, it looks really ugly

2021-12-15 09:44 UTC, eli1stark commented on lib/shared/providers/deep_link_service_pod.dart
> +    final navigatorKey = ref.watch(sNavigatorKeyPod);
remove

2021-12-15 09:44 UTC, eli1stark commented on lib/shared/providers/deep_link_service_pod.dart
> +    final startup = ref.watch(startupNotipod);
remove

2021-12-15 09:44 UTC, eli1stark commented on lib/shared/providers/deep_link_service_pod.dart
> +    return DeepLinkService(
`return DeepLinkService(this.read)`

2021-12-15 09:44 UTC, eli1stark commented on lib/shared/services/deep_link_service.dart
> +    required this.startup,
access navigatorKey and startup through reader

2021-12-15 09:44 UTC, eli1stark commented on lib/shared/services/deep_link_service.dart
> +class _UndefinedDeepLink extends StatelessWidget {
remove

2021-12-15 09:44 UTC, eli1stark commented on lib/shared/services/deep_link_service.dart
> +      default:
```
else {
   _logger.log(Level.INFO, 'Deep link is undefined');
}
```

2021-12-15 09:44 UTC, eli1stark commented on plugins/simple_kit/lib/src/referral_invite/simple_referral_invite_body.dart
> +              Baseline(
repeated component

2021-12-15 09:44 UTC, eli1stark commented on plugins/simple_kit/lib/src/referral_invite/simple_referral_invite_body.dart
> +              Baseline(
repeated component

2021-12-15 09:44 UTC, eli1stark commented on plugins/simple_kit/lib/src/referral_invite/simple_referral_invite_body.dart
> +              Baseline(
repeated component

2021-12-15 09:44 UTC, eli1stark commented on plugins/simple_kit/lib/src/referral_invite/simple_referral_invite_body.dart
> +              Baseline(
repeated component

2021-12-15 09:44 UTC, eli1stark commented on lib/app/screens/market/view/components/market_banner/market_banner.dart
> +  Uri _parseDeepLink(String deepLink) {
remove this function

2021-12-15 10:33 UTC, eli1stark approved these changes

2021-12-15 10:34 UTC, merged