Sp UI-764 > Referral gift
MyJetWallet/Flutter.JetWallet pull request #312
Opened 2021-12-15 17:50 UTC by DenisMartych

2021-12-15 22:10 UTC, VovaMedvediev commented on lib/app/screens/portfolio/view/components/portfolio_with_balance/portfolio_with_balance_header.dart
> +                          '\$15',
Should it be hardcoded or maybe in base currency?

2021-12-15 22:10 UTC, VovaMedvediev commented on lib/app/shared/features/referral_program_gift/provider/referral_gift_pod.dart
> +        referralProgramExist[0].conditions!,
Are you sure that conditions are not null?

2021-12-15 22:10 UTC, VovaMedvediev commented on lib/app/shared/features/rewards/helper/set_reward_description_item.dart
> +          ' after trading \$100 (${condition.parameters!.tradedAmount!.split('.')[0]}/${condition.parameters!.requiredAmount})',
same here

2021-12-15 22:10 UTC, VovaMedvediev commented on lib/service/services/referral_gift/service/referral_gift_service.dart
> +  static final logger = Logger('ReferralGiftService');
unused?

2021-12-15 22:10 UTC, VovaMedvediev commented on lib/service/services/referral_gift/service/services/check_all_conditions_passed_service.dart
> +import '../../../signal_r/model/campaign_response_model.dart';
maybe it directory name should be helpers instead of services

2021-12-16 09:22 UTC, eli1stark requested changes

2021-12-16 09:22 UTC, eli1stark commented on lib/service/services/referral_gift/service/services/find_referral_program_service.dart
> +List<CampaignModel> findReferralProgramService(List<CampaignModel> campaigns) {
this is not service, this is helper

2021-12-16 09:22 UTC, eli1stark commented on lib/service/services/referral_gift/service/referral_gift_service.dart
> +class ReferralGiftService {
remove this service, this is not service at all. There are 2 helpers

2021-12-16 11:18 UTC, DenisMartych commented on lib/app/screens/portfolio/view/components/portfolio_with_balance/portfolio_with_balance_header.dart
> +                          '\$15',
After talk with Pavel, it's hardcode

2021-12-16 11:19 UTC, DenisMartych commented on lib/app/shared/features/referral_program_gift/provider/referral_gift_pod.dart
> +        referralProgramExist[0].conditions!,
not null, because check it in referralProgramExist

2021-12-16 11:24 UTC, DenisMartych commented on lib/app/shared/features/rewards/helper/set_reward_description_item.dart
> +          ' after trading \$100 (${condition.parameters!.tradedAmount!.split('.')[0]}/${condition.parameters!.requiredAmount})',
always, because tradeCondition always has tradeAmount

2021-12-16 11:25 UTC, DenisMartych commented on lib/service/services/referral_gift/service/referral_gift_service.dart
> +  static final logger = Logger('ReferralGiftService');
remove

2021-12-16 11:34 UTC, DenisMartych commented on lib/service/services/referral_gift/service/services/find_referral_program_service.dart
> +List<CampaignModel> findReferralProgramService(List<CampaignModel> campaigns) {
refactor findReferralProgramService to helper findReferralProgram

2021-12-16 11:34 UTC, DenisMartych commented on lib/service/services/referral_gift/service/services/check_all_conditions_passed_service.dart
> +import '../../../signal_r/model/campaign_response_model.dart';
done

2021-12-16 11:34 UTC, DenisMartych commented on lib/service/services/referral_gift/service/referral_gift_service.dart
> +class ReferralGiftService {
done

2021-12-16 12:03 UTC, VovaMedvediev approved these changes

2021-12-16 12:40 UTC, merged