SPUI > 804: Sort rewards
MyJetWallet/Flutter.JetWallet pull request #326
Opened 2021-12-20 12:07 UTC by DenisMartych

2021-12-22 12:41 UTC, eli1stark commented
![screenshot-github dev-2021 12 22-14_40_37](https://user-images.githubusercontent.com/57593530/147094374-df1291b0-e70c-431b-8c2c-36cc8a93a034.png)
Split into 2 folders inside notifier layer
and rename `notifiers` to `notifier`

2021-12-22 12:46 UTC, eli1stark commented on lib/app/shared/features/rewards/notifier/rewards_notifier.dart
> +    return sortedRewards;
add space

2021-12-22 13:19 UTC, eli1stark requested changes

2021-12-22 14:04 UTC, eli1stark commented
Sorting example
```dart
class TestClass1 {
  TestClass1({
    required this.weight,
    required this.value,
  });

  final int weight;
  final String value;
}

class TestClass2 {
  TestClass2({
    required this.weight,
    required this.value,
  });

  final int weight;
  final String value;
}

final array1 = [
  TestClass1(weight: 9, value: 'Hello 9'),
  TestClass1(weight: 1, value: 'Hello 1'),
  TestClass1(weight: 3, value: 'Hello 3'),
  TestClass1(weight: 1, value: 'Hello 1'),
  TestClass1(weight: 34, value: 'Hello 34'),
  TestClass1(weight: 4, value: 'Hello 4'),
];

final array2 = [
  TestClass2(weight: 55, value: 'Hello2 55'),
  TestClass2(weight: 1, value: 'Hello2 1'),
  TestClass2(weight: 6, value: 'Hello2 6'),
  TestClass2(weight: 8, value: 'Hello2 8'),
  TestClass2(weight: 12, value: 'Hello2 12'),
  TestClass2(weight: 4, value: 'Hello2 4'),
];

class CombinedTest {
  CombinedTest({
    this.test1,
    this.test2,
  });

  final TestClass1? test1;
  final TestClass2? test2;
}

void sorting() {
  final arrayToReturn = <CombinedTest>[];
  final newArray1 = List<TestClass1>.from(array1);
  final newArray2 = List<TestClass2>.from(array2);

  for (final element in newArray1) {
    arrayToReturn.add(CombinedTest(test1: element));
  }

  for (final element in newArray2) {
    arrayToReturn.add(CombinedTest(test2: element));
  }

  arrayToReturn.sort((a, b) {
    final weight1 = a.test1?.weight ?? a.test2!.weight;
    final weight2 = b.test1?.weight ?? b.test2!.weight;

    return weight1.compareTo(weight2);
  });

  for (final element in arrayToReturn) {
    final weight = element.test1?.weight ?? element.test2!.weight;
    final value = element.test1?.value ?? element.test2!.value;

    print('WEIGHT: $weight ; VALUE: $value');
  }
}
```

2021-12-22 14:30 UTC, DenisMartych commented on lib/app/shared/features/rewards/notifier/rewards_notifier.dart
> +  List<CombinedRewardModel> sortRewardsByWeight(RewardsModel rewards) {
done

2021-12-22 14:31 UTC, DenisMartych commented on lib/app/shared/features/rewards/notifier/rewards_notifier.dart
> +    final sortedRewards = sortRewardsByWeight(rewards);
done

2021-12-22 14:31 UTC, DenisMartych commented on lib/app/shared/features/rewards/notifier/rewards_notifier.dart
> +    updateRewards(sortedRewards);
done

2021-12-22 16:24 UTC, DenisMartych commented on lib/app/shared/features/rewards/notifier/rewards_notipod.dart
> +final rewardsNotipod = StateNotifierProvider.autoDispose<RewardsNotifier,
done

2021-12-22 16:49 UTC, DenisMartych commented on lib/app/shared/features/rewards/notifier/rewards_notipod.dart
> +final rewardsNotipod = StateNotifierProvider.autoDispose<RewardsNotifier,
done

2021-12-22 16:49 UTC, DenisMartych commented on lib/app/shared/features/rewards/notifier/rewards_notipod.dart
> +
done

2021-12-22 17:05 UTC, DenisMartych commented on lib/app/shared/features/rewards/view/rewards.dart
>      final randomNumber = Random();
done

2021-12-22 17:07 UTC, DenisMartych commented on lib/app/shared/features/rewards/view/rewards.dart
>                  circleAvatarColor: setBannerColor(
done

2021-12-22 17:24 UTC, DenisMartych commented on lib/app/shared/features/rewards/view/rewards.dart
>                  circleAvatarColor: setBannerColor(
done

2021-12-23 09:17 UTC, eli1stark commented on lib/app/shared/features/rewards/notifier/reward/rewards_notipod.dart
> +    final rewards = RewardsModel(
asked in dm

2021-12-23 09:17 UTC, eli1stark commented on lib/app/shared/features/rewards/notifier/reward/rewards_notipod.dart
> +List<CampaignOrReferralModel> _sorting(RewardsModel rewards) {
rename to _sort

2021-12-28 13:59 UTC, DenisMartych commented on lib/app/shared/features/rewards/notifier/reward/rewards_notipod.dart
> +    final rewards = RewardsModel(
done

2021-12-28 14:00 UTC, DenisMartych commented on lib/app/shared/features/rewards/notifier/reward/rewards_notipod.dart
> +List<CampaignOrReferralModel> _sorting(RewardsModel rewards) {
done

2021-12-28 14:25 UTC, eli1stark requested changes

2021-12-28 14:25 UTC, eli1stark commented on lib/app/shared/features/rewards/view/rewards.dart
> +            if (_displaySThreeStepsRewardBanner(item)) ...[
_displayThreeStepsRewardBanner

2021-12-28 14:25 UTC, eli1stark commented on lib/app/shared/features/rewards/view/rewards.dart
> +  bool _displaySRewardBanner(CampaignOrReferralModel item) {
rename to _displayRewardBanner

2021-12-28 14:25 UTC, eli1stark commented on lib/app/shared/features/rewards/view/rewards.dart
> +  bool _displaySThreeStepsRewardBanner(CampaignOrReferralModel item) {
rename to _displayThreeStepsRewardBanner

2021-12-28 16:30 UTC, eli1stark commented on lib/app/shared/features/rewards/helper/set_reward_description_style.dart
> +      final textStyle = TextStyle(
return just TextStyle

2021-12-28 16:30 UTC, eli1stark commented on lib/app/shared/features/rewards/helper/set_reward_description_style.dart
> +      final textStyle = TextStyle(
why are you using TextStyle instead of our own fonts?

2021-12-28 16:30 UTC, eli1stark commented on lib/app/shared/features/rewards/helper/set_reward_description_style.dart
> +          return TextStyle(
why are you using TextStyle instead of our own fonts?

2021-12-28 16:30 UTC, eli1stark commented on lib/app/shared/features/rewards/helper/set_reward_description_style.dart
>      return TextStyle(
why are you using TextStyle instead of our own fonts?

2021-12-28 16:30 UTC, eli1stark commented on lib/app/shared/features/rewards/helper/set_reward_description_style.dart
>        return TextStyle(
why are you using TextStyle instead of our own fonts?

2021-12-28 16:48 UTC, DenisMartych commented on lib/app/shared/features/rewards/view/rewards.dart
> +  bool _displaySThreeStepsRewardBanner(CampaignOrReferralModel item) {
done

2021-12-28 16:48 UTC, DenisMartych commented on lib/app/shared/features/rewards/view/rewards.dart
> +  bool _displaySRewardBanner(CampaignOrReferralModel item) {
done

2021-12-28 17:14 UTC, DenisMartych commented on lib/app/shared/features/rewards/helper/set_reward_description_style.dart
> +      final textStyle = TextStyle(
done
change on this
style: sBodyText1Style.copyWith(
            color: setRewardDescriptionStyle(
              condition,
              conditions,
              colors,
            ),
          ),

2021-12-28 17:14 UTC, DenisMartych commented on lib/app/shared/features/rewards/helper/set_reward_description_style.dart
> +          return TextStyle(
done
change on this
style: sBodyText1Style.copyWith(
            color: setRewardDescriptionStyle(
              condition,
              conditions,
              colors,
            ),
          ),

2021-12-28 17:14 UTC, DenisMartych commented on lib/app/shared/features/rewards/helper/set_reward_description_style.dart
>      return TextStyle(
done
change on this
style: sBodyText1Style.copyWith(
            color: setRewardDescriptionStyle(
              condition,
              conditions,
              colors,
            ),
          ),

2021-12-28 17:14 UTC, DenisMartych commented on lib/app/shared/features/rewards/helper/set_reward_description_style.dart
>        return TextStyle(
done
change on this
style: sBodyText1Style.copyWith(
            color: setRewardDescriptionStyle(
              condition,
              conditions,
              colors,
            ),
          ),

2021-12-29 06:22 UTC, merged