SPUI-724 > Display phone number after set
MyJetWallet/Flutter.JetWallet pull request #337
Opened 2021-12-23 17:50 UTC by DenisMartych

2021-12-28 07:05 UTC, eli1stark requested changes

2021-12-28 07:05 UTC, eli1stark commented on lib/shared/features/phone_verification/phone_verification_confirm/notifier/phone_verification_confirm_notifier.dart
> +        userInfo.updatePhone(state.phoneNumber);
userInfoN.updatePhone(state.phoneNumber);

2021-12-28 07:05 UTC, eli1stark commented on lib/shared/features/phone_verification/phone_verification_confirm/notifier/phone_verification_confirm_notifier.dart
> +        final userInfo = read(userInfoNotipod.notifier);
remove

2021-12-29 18:13 UTC, DenisMartych commented on lib/shared/features/phone_verification/phone_verification_confirm/notifier/phone_verification_confirm_notifier.dart
> +        userInfo.updatePhone(state.phoneNumber);
done

2021-12-29 18:13 UTC, DenisMartych commented on lib/shared/features/phone_verification/phone_verification_confirm/notifier/phone_verification_confirm_notifier.dart
> +        final userInfo = read(userInfoNotipod.notifier);
done

2022-01-03 18:02 UTC, closed without merging