SPUI-865 > Fix enter number
MyJetWallet/Flutter.JetWallet pull request #346
Opened 2021-12-29 16:45 UTC by DenisMartych

2021-12-29 19:54 UTC, eli1stark requested changes

2021-12-29 19:54 UTC, eli1stark commented on lib/app/shared/features/profile_details/view/components/change_phone_number/change_phone_number.dart
> +class ChangePhoneNumber extends StatefulHookWidget {
Make it HookWidget and remove observers

2021-12-29 19:54 UTC, eli1stark commented on lib/app/shared/features/profile_details/view/components/change_phone_number/change_phone_number.dart
> +    final phoneNumberInput = useProvider(phoneNumberNotipod);
rename to state

2021-12-29 19:54 UTC, eli1stark commented on lib/app/shared/features/profile_details/view/components/change_phone_number/change_phone_number.dart
>      final phoneNumberN = useProvider(phoneNumberNotipod.notifier);
rename to notifier

2021-12-29 19:54 UTC, eli1stark commented on lib/app/shared/features/profile_details/view/components/change_phone_number/change_phone_number.dart
> +                  phoneNumberN.updateCountryCode(
why do you updating this?

2021-12-29 19:54 UTC, eli1stark commented on lib/app/shared/features/profile_details/view/components/change_phone_number/change_phone_number.dart
> +                  phoneNumberN.updatePhoneNumber(
why do you updating this? you can access the phone number through phoneNumberInput.phoneNumberController.text

2021-12-29 19:54 UTC, eli1stark commented on lib/shared/notifiers/phone_number_notifier/phone_number_state.dart
> +    @Default('') String dialCodeSearch,
sort

2022-01-04 10:05 UTC, DenisMartych commented on lib/app/shared/features/profile_details/view/components/change_phone_number/change_phone_number.dart
> +class ChangePhoneNumber extends StatefulHookWidget {
done

2022-01-04 10:05 UTC, DenisMartych commented on lib/app/shared/features/profile_details/view/components/change_phone_number/change_phone_number.dart
> +    final phoneNumberInput = useProvider(phoneNumberNotipod);
done

2022-01-04 10:05 UTC, DenisMartych commented on lib/app/shared/features/profile_details/view/components/change_phone_number/change_phone_number.dart
>      final phoneNumberN = useProvider(phoneNumberNotipod.notifier);
done

2022-01-04 10:05 UTC, DenisMartych commented on lib/app/shared/features/profile_details/view/components/change_phone_number/change_phone_number.dart
> +                  phoneNumberN.updatePhoneNumber(
remove updatePhoneNumber

2022-01-04 10:05 UTC, DenisMartych commented on lib/shared/notifiers/phone_number_notifier/phone_number_state.dart
> +    @Default('') String dialCodeSearch,
done

2022-01-04 10:11 UTC, DenisMartych commented on lib/app/shared/features/profile_details/view/components/change_phone_number/change_phone_number.dart
> +                  phoneNumberN.updateCountryCode(
need update, if not pick code, we set default value

2022-01-04 10:23 UTC, eli1stark commented on lib/app/shared/features/profile_details/view/components/bottom_sheet/change_phone_dial_code_picker.dart
> +void changePhoneDialCodePicker(BuildContext context) {
rename to showPhoneDialCodePicker

2022-01-04 10:26 UTC, eli1stark commented on lib/app/shared/features/profile_details/view/components/change_phone_number/change_phone_number.dart
> +                          phone,
remove comma

2022-01-04 10:29 UTC, eli1stark commented on lib/shared/notifiers/phone_number_notifier/phone_number_state.dart
> +    @Default('') String dialCodeSearch,
no, it's not done

2022-01-04 10:29 UTC, eli1stark commented on lib/shared/notifiers/phone_number_notifier/phone_number_state.dart
> +    @Default('') String dialCodeSearch,
@Default('') String? countryCode,

2022-01-04 10:30 UTC, eli1stark commented on lib/shared/notifiers/phone_number_notifier/phone_number_state.dart
> +    @Default('') String dialCodeSearch,
can't have Default and be nullable at the same time

2022-01-04 10:32 UTC, eli1stark commented on lib/app/shared/features/profile_details/view/profile_details.dart
> +                        navigatorPush(
use ChangePhoneNumber.push() instead

2022-01-04 10:42 UTC, eli1stark commented on lib/shared/notifiers/phone_number_notifier/phone_number_state.dart
> +    @Default('') String dialCodeSearch,
but this field will be removed anyway (read coments I left)

2022-01-04 10:42 UTC, eli1stark commented on lib/app/shared/features/profile_details/view/components/change_phone_number/change_phone_number.dart
> +                  phoneNumberN.updateCountryCode(
```dart
                notifier.updateCountryCode(
                  state.dialCodeController.text,
                );
```

you have this info in your dialCodeController.text, so this function (updateCountryCode) and countryCode field is useless, remove them. Instead create in your phoneNumberState getter called country code that looks like this:
```dart
String get countryCode {
   return dialCodeController.text
}
```

2022-01-04 10:48 UTC, eli1stark commented on lib/app/shared/features/profile_details/view/components/change_phone_number/change_phone_number.dart
> +            notifier.clearCountryCode();
why do you need this?
your provider is autoDisposing authomatically
remove this function from notifier since there is no need for it, unless you have some explanation. And if we are left with just Navigator.pop(context) you can remove  onBackButtonTap callback because this is the default behaviour

2022-01-04 10:51 UTC, eli1stark commented on lib/shared/notifiers/phone_number_notifier/phone_number_notifier.dart
> +  void clearCountryCode() {
remove

2022-01-04 11:06 UTC, eli1stark commented on lib/shared/features/phone_verification/phone_verification_confirm/notifier/phone_verification_confirm_notifier.dart
> +        _phoneNumberN.updatePhoneNumber('');
autodispose will do the work, so it's redundant code

2022-01-04 11:32 UTC, DenisMartych commented on lib/shared/notifiers/phone_number_notifier/phone_number_state.dart
> +    @Default('') String dialCodeSearch,
done

2022-01-04 11:33 UTC, DenisMartych commented on lib/app/shared/features/profile_details/view/components/bottom_sheet/change_phone_dial_code_picker.dart
> +void changePhoneDialCodePicker(BuildContext context) {
done

2022-01-04 11:33 UTC, DenisMartych commented on lib/app/shared/features/profile_details/view/profile_details.dart
> +                        navigatorPush(
done

2022-01-04 14:01 UTC, DenisMartych commented on lib/app/shared/features/profile_details/view/components/change_phone_number/change_phone_number.dart
> +                  phoneNumberN.updateCountryCode(
done

2022-01-04 14:03 UTC, DenisMartych commented on lib/app/shared/features/profile_details/view/components/change_phone_number/change_phone_number.dart
> +                          phone,
done

2022-01-06 10:22 UTC, merged