SPUI-850 > Wallet screen UI
MyJetWallet/Flutter.JetWallet pull request #351
Opened 2022-01-05 09:15 UTC by VovaMedvediev

2022-01-05 09:20 UTC, eli1stark commented
return back assets for fast_rsa and other functionality, reminder before review

2022-01-14 11:11 UTC, eli1stark requested changes

2022-01-14 11:11 UTC, eli1stark commented on lib/app/shared/features/wallet/view/components/wallet_body/wallet_body.dart
> +    var walletBackground = 'assets/images/green_wallet_gradient.svg';
move harcoded asset names to constants in shared folder, fix all occurences

2022-01-14 11:11 UTC, eli1stark commented on lib/app/shared/features/wallet/view/components/wallet_body/wallet_body.dart
> +      walletBackground = 'assets/images/red_wallet_gradient.svg';
move harcoded asset names to constants in shared folder, fix all occurences

2022-01-14 11:11 UTC, eli1stark commented on lib/app/shared/features/wallet/view/components/wallet_body/wallet_body.dart
> +class WalletBody extends StatefulHookWidget {
add todo: refactor this widget

2022-01-14 11:11 UTC, eli1stark commented on lib/shared/components/app_builder.dart
> +class AppBuilder extends HookWidget {
remove this widget, this is already implemented in the core, remember?, looks like your old changes want to override the new ones

2022-01-14 11:11 UTC, eli1stark commented on plugins/simple_kit/lib/src/notifications/view/show_simple_notification.dart
> +  WidgetsBinding.instance?.addPostFrameCallback(
why you did this?

2022-01-14 11:11 UTC, eli1stark commented on plugins/simple_kit/lib/src/shared/components/simple_skeleton_text_loader.dart
> +    this.height = 16,
make this parameter required to make this component more general without default size

2022-01-14 11:11 UTC, eli1stark commented on plugins/simple_kit/lib/src/shared/components/simple_skeleton_text_loader.dart
> +    this.width = 80,
make this parameter required to make this component more general without default size

2022-01-14 11:11 UTC, eli1stark commented on plugins/simple_kit/lib/src/buttons/basic_buttons/base/simple_base_button.dart
> +    this.addIconPadding = true,
rename to enableIconPadding

2022-01-15 13:28 UTC, VovaMedvediev commented on assets/images/deposit_icon.svg
> +<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
done

2022-01-15 13:28 UTC, VovaMedvediev commented on assets/images/minus_icon.svg
> +<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
done

2022-01-15 13:28 UTC, VovaMedvediev commented on assets/images/paid_interest_rate_icon.svg
> +<svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
done

2022-01-15 13:28 UTC, VovaMedvediev commented on assets/images/plus_icon.svg
> +<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
done

2022-01-15 13:28 UTC, VovaMedvediev commented on assets/images/receive_by_phone_icon.svg
> +<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
done

2022-01-15 13:28 UTC, VovaMedvediev commented on assets/images/reward_payment_icon.svg
> +<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
done

2022-01-15 13:28 UTC, VovaMedvediev commented on assets/images/send_by_phone_icon.svg
> +<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
done

2022-01-15 13:28 UTC, VovaMedvediev commented on assets/images/send_icon.svg
> +<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
done

2022-01-15 13:28 UTC, VovaMedvediev commented on assets/images/swap_icon.svg
> +<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
done

2022-01-15 13:28 UTC, VovaMedvediev commented on assets/images/withdrawal_fee_icon.svg
> +<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
done

2022-01-15 13:30 UTC, VovaMedvediev commented on lib/app/shared/features/wallet/view/components/action_button/action_button.dart
> +                        ? Interval(
done

2022-01-15 13:30 UTC, VovaMedvediev commented on lib/app/shared/features/wallet/view/components/action_button/action_button.dart
> +                        : Interval(
done

2022-01-15 13:31 UTC, VovaMedvediev commented on lib/app/shared/features/wallet/view/components/action_button/action_button.dart
> +                        ? Interval(
done

2022-01-15 13:31 UTC, VovaMedvediev commented on lib/app/shared/features/wallet/view/components/action_button/action_button.dart
> +                        : Interval(
done

2022-01-15 13:31 UTC, VovaMedvediev commented on lib/app/shared/features/wallet/view/components/wallet_body/components/card_block/components/wallet_card.dart
> +                  style: sSubtitle3Style.copyWith(color: colors.white),
done

2022-01-15 13:32 UTC, VovaMedvediev commented on lib/app/shared/features/wallet/view/components/wallet_body/components/card_block/components/wallet_card.dart
> +                style: sBodyText2Style.copyWith(color: colors.grey1),
done

2022-01-15 13:32 UTC, VovaMedvediev commented on lib/app/shared/features/wallet/model/transaction_icon_model.dart
> +class TransactionIconModel {
done

2022-01-15 13:32 UTC, VovaMedvediev commented on lib/app/shared/features/wallet/view/components/wallet_body/components/card_block/components/wallet_card_collapsed.dart
> +              style: sBodyText2Style.copyWith(color: colors.grey1),
done

2022-01-15 13:32 UTC, VovaMedvediev commented on lib/app/shared/features/wallet/view/components/wallet_body/components/transactions_list_item/components/transaction_details/components/common_transaction_details_block.dart
> +          style: sBodyText2Style.copyWith(color: colors.grey2),
done

2022-01-15 13:33 UTC, VovaMedvediev commented on lib/app/shared/features/wallet/view/components/wallet_body/components/transactions_list_item/components/transaction_details/receive_details.dart
> +                    style: sBodyText2Style.copyWith(color: colors.grey1),
done

2022-01-15 13:33 UTC, VovaMedvediev commented on lib/app/shared/features/wallet/view/components/wallet_body/components/transactions_list_item/transaction_list_item.dart
> +  String _icon(OperationType type) {
refactored to usage of simple_kit_icons

2022-01-15 13:35 UTC, VovaMedvediev commented on lib/app/shared/features/wallet/view/components/wallet_body/wallet_body.dart
> +    var walletBackground = 'assets/images/green_wallet_gradient.svg';
done

2022-01-15 13:35 UTC, VovaMedvediev commented on lib/app/shared/features/wallet/view/components/wallet_body/wallet_body.dart
> +      walletBackground = 'assets/images/red_wallet_gradient.svg';
done

2022-01-15 13:35 UTC, VovaMedvediev commented on lib/app/shared/features/wallet/view/components/wallet_body/wallet_body.dart
> +class WalletBody extends StatefulHookWidget {
done

2022-01-15 13:36 UTC, VovaMedvediev commented on lib/shared/components/app_builder.dart
> +class AppBuilder extends HookWidget {
removed

2022-01-15 13:40 UTC, VovaMedvediev commented on plugins/simple_kit/lib/src/buttons/basic_buttons/base/simple_base_button.dart
> +    this.addIconPadding = true,
done

2022-01-15 13:40 UTC, VovaMedvediev commented on plugins/simple_kit/lib/src/shared/components/simple_skeleton_text_loader.dart
> +    this.width = 80,
done

2022-01-15 13:40 UTC, VovaMedvediev commented on plugins/simple_kit/lib/src/shared/components/simple_skeleton_text_loader.dart
> +    this.height = 16,
done

2022-01-15 14:32 UTC, VovaMedvediev commented on plugins/simple_kit/lib/src/notifications/view/show_simple_notification.dart
> +  WidgetsBinding.instance?.addPostFrameCallback(
It wasn't working at Wallet Screen without addPostFrameCallback. But I tested it and it is working. Deleted

2022-01-15 14:46 UTC, VovaMedvediev commented on assets/images/paid_interest_rate_icon.svg
> +<svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
done

2022-01-15 16:10 UTC, merged