SPUI-911 > Add interest rate bottom sheet
MyJetWallet/Flutter.JetWallet pull request #352
Opened 2022-01-05 23:53 UTC by VovaMedvediev

2022-01-14 11:23 UTC, eli1stark requested changes

2022-01-14 11:23 UTC, eli1stark commented on ios/Runner.xcodeproj/project.pbxproj
> +		42BF60932785D73D0067C1F2 /* GoogleService-Info.plist in Resources */ = {isa = PBXBuildFile; fileRef = 42BF60922785D73D0067C1F2 /* GoogleService-Info.plist */; };
is it possible to make commit without `project.pbxproj`

2022-01-14 11:23 UTC, eli1stark commented on lib/app/shared/features/wallet/view/components/wallets_body/components/card_block/components/wallet_card.dart
> +          children: [
refactor please

2022-01-14 11:23 UTC, eli1stark commented on lib/app/shared/features/wallet/view/components/wallets_body/components/card_block/components/wallet_card.dart
> +      child: Container(
and refactor this as well

2022-01-15 15:48 UTC, VovaMedvediev commented on ios/Runner.xcodeproj/project.pbxproj
> +		42BF60932785D73D0067C1F2 /* GoogleService-Info.plist in Resources */ = {isa = PBXBuildFile; fileRef = 42BF60922785D73D0067C1F2 /* GoogleService-Info.plist */; };
deleted changes in project.pbxproj

2022-01-15 23:09 UTC, VovaMedvediev commented on lib/app/shared/features/wallet/view/components/wallets_body/components/card_block/components/wallet_card.dart
> +          children: [
refactored

2022-01-15 23:09 UTC, VovaMedvediev commented on lib/app/shared/features/wallet/view/components/wallets_body/components/card_block/components/wallet_card.dart
> +      child: Container(
refactored

2022-01-20 09:31 UTC, merged