SPUI-1125 > Crisp
MyJetWallet/Flutter.JetWallet pull request #420
Opened 2022-02-11 15:16 UTC by VovaMedvediev

2022-02-15 11:24 UTC, eli1stark requested changes

2022-02-15 11:24 UTC, eli1stark commented on lib/shared/providers/device_info_pod.dart
> +    DeviceInfoModel? uid;
rename `uid` to `info`

2022-02-15 11:24 UTC, eli1stark commented on lib/shared/providers/device_info_pod.dart
> +final deviceInfoPod = Provider<DeviceInfoModel?>(
make DeviceInfoModel non-nullable like it was before with deviceUid

2022-02-15 11:24 UTC, eli1stark commented on lib/shared/model/device_info/device_info_model.dart
> +    @Default('') String sdk,
move Default parameters up and required down

2022-02-15 11:24 UTC, eli1stark commented on lib/shared/notifiers/user_info_notifier/user_info_notifier.dart
> +    required String countryOfResidence,
update clear method of the UserInfoNotifier

2022-02-15 11:24 UTC, eli1stark commented on lib/shared/model/device_info/device_info_model.dart
> +    @Default('') String sdk,
And you can also make other info default as well because you will need a placeholder in deviceInfoPod in order to make the return type non-nullable

2022-02-15 11:24 UTC, eli1stark commented on lib/auth/shared/notifiers/authentication_notifier/authentication_notifier.dart
> +      final deviceInfoModel = await deviceInfo();
use deviceInfoPod instead, because its value is already cached

2022-02-15 11:24 UTC, eli1stark commented on lib/shared/helpers/device_info.dart
> +  return null;
add finally instead in order to have one return instead of 2
  } finally {
    return null;
  }

2022-02-17 11:07 UTC, VovaMedvediev commented on lib/shared/providers/device_info_pod.dart
> +    DeviceInfoModel? uid;
done

2022-02-17 11:19 UTC, VovaMedvediev commented on lib/shared/providers/device_info_pod.dart
> +final deviceInfoPod = Provider<DeviceInfoModel?>(
done

2022-02-17 11:32 UTC, VovaMedvediev commented on lib/shared/model/device_info/device_info_model.dart
> +    @Default('') String sdk,
All parameters are default and not required now

2022-02-17 11:35 UTC, VovaMedvediev commented on lib/shared/notifiers/user_info_notifier/user_info_notifier.dart
> +    required String countryOfResidence,
updated

2022-02-17 11:35 UTC, VovaMedvediev commented on lib/auth/shared/notifiers/authentication_notifier/authentication_notifier.dart
> +      final deviceInfoModel = await deviceInfo();
done

2022-02-17 11:36 UTC, VovaMedvediev commented on lib/shared/helpers/device_info.dart
> +  return null;
actually return statement is not needed here. There are no function throwing exceptions

2022-02-17 13:38 UTC, eli1stark approved these changes

2022-02-18 11:59 UTC, merged