SPUI-1261 > Change allow camera ui
MyJetWallet/Flutter.JetWallet pull request #495
Opened 2022-03-17 20:04 UTC by DenisMartych

2022-03-23 09:13 UTC, eli1stark requested changes

2022-03-23 09:13 UTC, eli1stark commented on lib/app/shared/features/kyc/view/components/allow_camera/allow_camera.dart
> +            title: state.permissionDenied
refactor title to function and name it `headerTitle()`

2022-03-23 09:13 UTC, eli1stark commented on lib/app/shared/features/kyc/view/components/allow_camera/allow_camera.dart
add `final size  = MediaQuery.of(context).size;`

2022-03-23 09:13 UTC, eli1stark commented on lib/app/shared/features/kyc/view/components/allow_camera/allow_camera.dart
> +                  height: MediaQuery.of(context).size.width * 0.6,
add `size.width * 0.6` instead

2022-03-23 09:13 UTC, eli1stark commented on lib/app/shared/features/kyc/view/components/allow_camera/allow_camera.dart
> +            title: state.permissionDenied
reuse private function

2022-03-23 09:13 UTC, eli1stark commented on lib/app/shared/features/kyc/view/components/allow_camera/allow_camera.dart
you can declare function `headerTitle()` after `size` declaration, don't forget space between them

2022-03-23 11:57 UTC, DenisMartych commented on lib/app/shared/features/kyc/view/components/allow_camera/allow_camera.dart
> +            title: state.permissionDenied
done

2022-03-23 12:00 UTC, DenisMartych commented on lib/app/shared/features/kyc/view/components/allow_camera/allow_camera.dart
done

2022-03-23 12:00 UTC, DenisMartych commented on lib/app/shared/features/kyc/view/components/allow_camera/allow_camera.dart
> +                  height: MediaQuery.of(context).size.width * 0.6,
done

2022-03-24 09:33 UTC, eli1stark requested changes

2022-03-24 09:33 UTC, eli1stark commented on lib/app/shared/features/kyc/view/components/allow_camera/allow_camera.dart
> +    return status
use if statement instead

2022-03-24 13:59 UTC, DenisMartych commented on lib/app/shared/features/kyc/view/components/allow_camera/allow_camera.dart
> +    return status
done

2022-03-24 17:54 UTC, merged