SPUI-1261 > Add dynamic gift bonus
MyJetWallet/Flutter.JetWallet pull request #496
Opened 2022-03-18 10:05 UTC by DenisMartych

2022-03-24 12:20 UTC, eli1stark requested changes

2022-03-24 12:20 UTC, eli1stark commented on lib/app/screens/portfolio/view/components/portfolio_with_balance/portfolio_with_balance_header.dart
> +      if (item.campaign != null) {
`if (item.campaign?.conditions?.isNotEmpty ?? false)`

2022-03-24 12:20 UTC, eli1stark commented on lib/app/screens/portfolio/view/components/portfolio_with_balance/portfolio_with_balance_header.dart
> +        if (item.campaign!.conditions != null &&
remove

2022-03-24 12:20 UTC, eli1stark commented on lib/app/screens/portfolio/view/components/portfolio_with_balance/portfolio_with_balance_header.dart
> +    var bonusGift = Decimal.zero;
add space

2022-03-24 15:09 UTC, DenisMartych commented on lib/app/screens/portfolio/view/components/portfolio_with_balance/portfolio_with_balance_header.dart
> +      if (item.campaign != null) {
done

2022-03-24 15:09 UTC, DenisMartych commented on lib/app/screens/portfolio/view/components/portfolio_with_balance/portfolio_with_balance_header.dart
> +        if (item.campaign!.conditions != null &&
done

2022-03-24 17:57 UTC, eli1stark requested changes

2022-03-24 17:57 UTC, eli1stark commented on lib/app/screens/portfolio/view/components/portfolio_header.dart
> +      if (item.campaign != null) {
remove, redundant

2022-03-24 17:57 UTC, eli1stark commented on lib/app/screens/portfolio/view/components/portfolio_header.dart
> +                          margin: (_giftBonus(rewards) != '')
use `_giftBonus(rewards).isNotEmpty` instead

2022-03-25 10:29 UTC, DenisMartych commented on lib/app/screens/portfolio/view/components/portfolio_header.dart
> +                          margin: (_giftBonus(rewards) != '')
done

2022-03-25 10:30 UTC, DenisMartych commented on lib/app/screens/portfolio/view/components/portfolio_header.dart
> +      if (item.campaign != null) {
done

2022-03-25 11:57 UTC, merged