SPUI-1263 > Deposit UI fixes
MyJetWallet/Flutter.JetWallet pull request #497
Opened 2022-03-20 20:17 UTC by VovaMedvediev

2022-03-23 08:48 UTC, eli1stark requested changes

2022-03-23 08:48 UTC, eli1stark commented on lib/app/shared/features/crypto_deposit/view/crypto_deposit.dart
> +class CryptoDeposit extends StatefulHookWidget {
use HookWidget instead

2022-03-23 08:48 UTC, eli1stark commented on lib/app/shared/features/crypto_deposit/view/crypto_deposit.dart
add `final controller = useScrollController();`
useScrollController hook will dispose scollController automatically

2022-03-23 08:48 UTC, eli1stark commented on lib/app/shared/features/crypto_deposit/view/crypto_deposit.dart
> +  void initState() {
remove

2022-03-23 08:48 UTC, eli1stark commented on lib/app/shared/features/crypto_deposit/view/crypto_deposit.dart
> +  late ScrollController _scrollController;
remove

2022-03-24 08:22 UTC, VovaMedvediev commented on plugins/simple_kit/lib/src/shared/components/qr_code_fields/simple_address_field_with_copy.dart
> +    this.scrollToFullCopyMessage,
done

2022-03-24 08:22 UTC, VovaMedvediev commented on plugins/simple_kit/lib/src/notifications/view/simple_notification_box.dart
> +                padding: const EdgeInsets.symmetric(vertical: 20),
done

2022-03-24 08:22 UTC, VovaMedvediev commented on lib/app/shared/features/crypto_deposit/view/crypto_deposit.dart
> +class CryptoDeposit extends StatefulHookWidget {
done

2022-03-24 08:22 UTC, VovaMedvediev commented on lib/app/shared/features/crypto_deposit/view/crypto_deposit.dart
done
cool, didn't know about this

2022-03-24 08:22 UTC, VovaMedvediev commented on lib/app/shared/features/crypto_deposit/view/crypto_deposit.dart
> +  void initState() {
done

2022-03-24 08:22 UTC, VovaMedvediev commented on lib/app/shared/features/crypto_deposit/view/crypto_deposit.dart
> +  late ScrollController _scrollController;
done

2022-03-24 11:57 UTC, merged