SPUI-1033 > Add search to actions
MyJetWallet/Flutter.JetWallet pull request #500
Opened 2022-03-21 14:29 UTC by DenisMartych

2022-03-24 13:23 UTC, eli1stark requested changes

2022-03-24 13:23 UTC, eli1stark commented on lib/app/shared/features/actions/helper/action_bottom_sheet_header.dart
> +            onChanged: (value) {
add callback instead

2022-03-24 13:23 UTC, eli1stark commented on lib/app/shared/features/actions/action_withdraw/action_withdraw.dart
> +    final actionBuyFiltered = useProvider(actionBuyFilteredStpod);
use notifier instead

2022-03-24 13:23 UTC, eli1stark commented on lib/app/shared/features/actions/action_withdraw/action_withdraw.dart
> +    if (actionBuyFiltered.state.isNotEmpty) {
put this logic

2022-03-24 13:23 UTC, eli1stark commented on lib/app/shared/features/actions/action_send/action_send.dart
> +    if (actionBuyFiltered.state.isNotEmpty) {
put this logic inside notifier

2022-03-24 13:23 UTC, eli1stark commented on lib/app/shared/features/actions/action_sell/action_sell.dart
> +    if (actionBuyFiltered.state.isNotEmpty) {
put this logic to notifier

2022-03-24 13:23 UTC, eli1stark commented on lib/app/shared/features/actions/action_sell/action_sell.dart
> +    final actionBuyFiltered = useProvider(actionBuyFilteredStpod);
use notifier instead

2022-03-24 13:23 UTC, eli1stark commented on lib/app/shared/features/actions/action_receive/action_receive.dart
> +    final actionBuyFiltered = useProvider(actionBuyFilteredStpod);
use notifier instead

2022-03-24 13:23 UTC, eli1stark commented on lib/app/shared/features/actions/action_receive/action_receive.dart
> +    if (actionBuyFiltered.state.isNotEmpty) {
put this logic to notifier

2022-03-24 13:23 UTC, eli1stark commented on lib/app/shared/features/actions/action_deposit/action_deposit.dart
> +    final actionBuyFiltered = useProvider(actionBuyFilteredStpod);
use notifier instead

2022-03-24 13:23 UTC, eli1stark commented on lib/app/shared/features/actions/action_deposit/action_deposit.dart
> +    if (actionBuyFiltered.state.isNotEmpty) {
put this logic to notifier

2022-03-24 13:23 UTC, eli1stark commented on lib/app/shared/features/actions/action_buy/action_buy.dart
> +    if (actionBuyFiltered.state.isNotEmpty) {
put this logic to the notifier

2022-03-24 13:23 UTC, eli1stark commented on lib/app/shared/features/actions/action_buy/action_buy.dart
> +    final actionBuyFiltered = useProvider(actionBuyFilteredStpod);
use notifier instead

2022-03-24 13:23 UTC, eli1stark commented on lib/app/shared/features/actions/action_withdraw/action_withdraw.dart
> +                  actionBuyFiltered.state = '';
you will probably don't need this

2022-03-24 13:23 UTC, eli1stark commented on lib/app/shared/features/actions/provider/action_buy_filtered_stpod.dart
> +final actionBuyFilteredStpod = StateProvider<String>((ref) {
replace by notifier

2022-03-24 13:23 UTC, eli1stark commented on lib/app/shared/features/actions/action_buy/action_buy.dart
> +    onDissmis: () => actionBuyFiltered.state = '',
remove everywhere

2022-03-24 15:29 UTC, DenisMartych commented on lib/app/shared/features/actions/helper/action_bottom_sheet_header.dart
> +    final actionBuyFiltered = useProvider(actionBuyFilteredStpod);
done

2022-03-24 15:32 UTC, DenisMartych commented on lib/app/shared/features/actions/helper/action_bottom_sheet_header.dart
> +    required this.name,
done

2022-03-24 15:33 UTC, DenisMartych commented on lib/app/shared/features/actions/helper/action_bottom_sheet_header.dart
> +            onChanged: (value) {
done

2022-03-28 08:44 UTC, DenisMartych commented on lib/app/shared/features/actions/action_buy/action_buy.dart
> +    final actionBuyFiltered = useProvider(actionBuyFilteredStpod);
done

2022-03-28 08:44 UTC, DenisMartych commented on lib/app/shared/features/actions/action_withdraw/action_withdraw.dart
> +                  actionBuyFiltered.state = '';
done

2022-03-28 08:44 UTC, DenisMartych commented on lib/app/shared/features/actions/provider/action_buy_filtered_stpod.dart
> +final actionBuyFilteredStpod = StateProvider<String>((ref) {
done

2022-03-28 08:45 UTC, DenisMartych commented on lib/app/shared/features/actions/action_buy/action_buy.dart
> +  final actionBuyFiltered = context.read(actionBuyFilteredStpod);
done

2022-03-28 08:45 UTC, DenisMartych commented on lib/app/shared/features/actions/action_buy/action_buy.dart
> +    onDissmis: () => actionBuyFiltered.state = '',
done

2022-03-28 08:45 UTC, DenisMartych commented on lib/app/shared/features/actions/action_send/action_send.dart
> +    if (actionBuyFiltered.state.isNotEmpty) {
done

2022-03-28 08:45 UTC, DenisMartych commented on lib/app/shared/features/actions/action_sell/action_sell.dart
> +    if (actionBuyFiltered.state.isNotEmpty) {
done

2022-03-28 08:45 UTC, DenisMartych commented on lib/app/shared/features/actions/action_sell/action_sell.dart
> +    final actionBuyFiltered = useProvider(actionBuyFilteredStpod);
done

2022-03-28 08:45 UTC, DenisMartych commented on lib/app/shared/features/actions/action_receive/action_receive.dart
> +    final actionBuyFiltered = useProvider(actionBuyFilteredStpod);
done

2022-03-28 08:45 UTC, DenisMartych commented on lib/app/shared/features/actions/action_receive/action_receive.dart
> +    if (actionBuyFiltered.state.isNotEmpty) {
done

2022-03-28 08:45 UTC, DenisMartych commented on lib/app/shared/features/actions/action_deposit/action_deposit.dart
> +    final actionBuyFiltered = useProvider(actionBuyFilteredStpod);
done

2022-03-28 08:46 UTC, DenisMartych commented on lib/app/shared/features/actions/action_buy/action_buy.dart
> +    if (actionBuyFiltered.state.isNotEmpty) {
done

2022-03-28 09:14 UTC, eli1stark requested changes

2022-03-28 09:14 UTC, eli1stark commented on lib/app/shared/features/actions/notifier/currencies_notipod.dart
> +final currenciesNotipod =
rename to `actionSearchNotipod`

2022-03-28 09:14 UTC, eli1stark commented on lib/app/shared/features/actions/provider/action_buy_filtered_stpod.dart
> +final actionBuyFilteredStpod = StateProvider.autoDispose<String>((ref) {
delete, everything should be inside notifier

2022-03-28 09:14 UTC, eli1stark commented on lib/app/shared/features/actions/notifier/currencies_notipod.dart
> +  final currencies = ref.watch(currenciesPod);
remove, because if this will be updated your notifier will be reseted

2022-03-28 09:14 UTC, eli1stark commented on lib/app/shared/features/actions/notifier/currencies_notipod.dart
> +  final search = ref.watch(actionBuyFilteredStpod);
remove

2022-03-28 09:14 UTC, eli1stark commented on lib/app/shared/features/actions/notifier/currencies_notifier.dart
> +class CurrenciesNotifier extends StateNotifier<List<CurrencyModel>> {
The state of this Notifier, aka `ActionSearchState` will be: 
1. `currencies`. Currencies you fetched from `currenciesPod` during int of this notifier
2. `filteredCurrencies`. Currencies you filtered based on `search` input
3. `search`. Current search input

2022-03-28 09:14 UTC, eli1stark commented on lib/app/shared/features/actions/notifier/currencies_notifier.dart
> +class CurrenciesNotifier extends StateNotifier<List<CurrencyModel>> {
Rename `CurrenciesNotifier` to `ActionSearchNotifier`

2022-03-28 09:14 UTC, eli1stark commented on lib/app/shared/features/actions/helper/action_bottom_sheet_header.dart
> +            onChanged: (value) {
it's not done, you haven't refactored calback

2022-03-28 09:14 UTC, eli1stark commented on lib/app/shared/features/actions/helper/action_bottom_sheet_header.dart
> +    final actionBuyFiltered = useProvider(actionBuyFilteredStpod);
it's not done, you haven't removed

2022-03-28 09:14 UTC, eli1stark commented on lib/app/shared/features/actions/helper/action_bottom_sheet_header.dart
> +    required this.name,
it's not done, there is no `onChanged` callback added

2022-03-28 09:14 UTC, eli1stark commented on lib/app/shared/features/actions/action_sell/action_sell.dart
>    Navigator.pop(context); // close BasicBottomSheet from Menu
add notifier = context.watch(actionSearchNotipod); Fix all occurrences across actions

2022-03-28 09:14 UTC, eli1stark commented on lib/app/shared/features/actions/action_sell/action_sell.dart
> +    pinned: const ActionBottomSheetHeader(
here you will provide `notifier.search` lambda. Fix all occurrences across actions

2022-03-28 09:14 UTC, eli1stark commented on lib/app/shared/features/actions/action_sell/action_sell.dart
> +    for (final currency in state) {
`final currency in state.filteredCurrencies`. Fix all occurrences across actions

2022-03-28 09:14 UTC, eli1stark commented on lib/app/shared/features/actions/notifier/currencies_notifier.dart
> +class CurrenciesNotifier extends StateNotifier<List<CurrencyModel>> {
The notifier will have 3 methods: 
1. private called `init`
2. public called `search`
3. private called `filter` that will be triggered inside `search` method

2022-03-28 10:41 UTC, DenisMartych commented on lib/app/shared/features/actions/helper/action_bottom_sheet_header.dart
> +    final actionBuyFiltered = useProvider(actionBuyFilteredStpod);
done

2022-03-28 10:42 UTC, DenisMartych commented on lib/app/shared/features/actions/helper/action_bottom_sheet_header.dart
> +    required this.name,
done

2022-03-28 10:43 UTC, DenisMartych commented on lib/app/shared/features/actions/helper/action_bottom_sheet_header.dart
> +            onChanged: (value) {
done

2022-03-28 18:52 UTC, merged