SPUI-719 - News
MyJetWallet/Flutter.JetWallet pull request #514
Opened 2022-03-24 11:17 UTC by DenisMartych

2022-03-28 19:45 UTC, eli1stark requested changes

2022-03-28 19:45 UTC, eli1stark commented on lib/app/screens/news/components/loading/loading_sliver_news_list.dart
> +        NewsListLoadingItem(
```dart
for (var i = 10; i >= 1; i--)
        NewsListLoadingItem(
          opacity: i / 10,
          removeDivider: i > 4 ? false : true,
        ),
```

2022-03-28 19:45 UTC, eli1stark commented on lib/app/screens/news/notifier/news_state.dart
> +    required List<NewsModel> newsItems,
use `@Default([])`

2022-03-28 19:45 UTC, eli1stark commented on lib/app/screens/news/notifier/news_notifier.dart
> +      newsItems: [],
remove since you are using `@Default`

2022-03-28 19:45 UTC, eli1stark commented on lib/app/screens/news/provider/news_fpod.dart
> +final newsInitFpod = FutureProvider.family.autoDispose<void, String?>(
bad, this is not what we learned. Remove this provider

2022-03-28 19:45 UTC, eli1stark commented on lib/app/screens/news/notifier/news_notifier.dart
> +  Future<void> initNews() async {
rename to `_init`

2022-03-28 19:45 UTC, eli1stark commented on lib/app/screens/news/notifier/news_notifier.dart
> +  );
call `_init` in constructor

2022-03-28 19:45 UTC, eli1stark commented on lib/app/screens/news/notifier/news_notifier.dart
> +      model,
remove comma

2022-03-28 19:45 UTC, eli1stark commented on lib/app/screens/news/notifier/news_notifier.dart
> +    _logger.log(notifier, 'initNews');
remove

2022-03-28 21:15 UTC, DenisMartych commented on lib/app/screens/news/components/loading/loading_sliver_news_list.dart
> +        NewsListLoadingItem(
done

2022-03-28 21:17 UTC, DenisMartych commented on lib/app/screens/news/notifier/news_state.dart
> +    required List<NewsModel> newsItems,
done

2022-03-28 21:18 UTC, DenisMartych commented on lib/app/screens/news/notifier/news_notifier.dart
> +      newsItems: [],
done

2022-03-28 21:20 UTC, DenisMartych commented on lib/app/screens/news/notifier/news_notifier.dart
> +  Future<void> initNews() async {
done

2022-03-28 21:22 UTC, DenisMartych commented on lib/app/screens/news/notifier/news_notifier.dart
> +  );
done, but this function is public

2022-03-28 21:22 UTC, DenisMartych commented on lib/app/screens/news/notifier/news_notifier.dart
> +      model,
done

2022-03-28 21:23 UTC, DenisMartych commented on lib/app/screens/news/notifier/news_notifier.dart
> +    _logger.log(notifier, 'initNews');
done

2022-03-29 11:00 UTC, DenisMartych commented on lib/app/screens/news/provider/news_fpod.dart
> +final newsInitFpod = FutureProvider.family.autoDispose<void, String?>(
done

2022-03-29 14:16 UTC, merged