SPUI-1021 > Create empty state for country search
MyJetWallet/Flutter.JetWallet pull request #516
Opened 2022-03-25 11:36 UTC by Anton-Tesenchuk

2022-03-28 20:34 UTC, eli1stark requested changes

2022-03-28 20:34 UTC, eli1stark commented on lib/app/shared/features/kyc/view/components/empty_state/empty_state.dart
> +    final state = useProvider(kycCountriesNotipod);
remove

2022-03-28 20:34 UTC, eli1stark commented on lib/app/shared/features/kyc/view/components/empty_state/empty_state.dart
> +class EmptyState extends HookWidget {
rename to `EmptySearchResult`

2022-03-28 20:34 UTC, eli1stark commented on lib/app/shared/features/kyc/view/components/empty_state/empty_state.dart
> +    Key? key,
add `required String text`

2022-03-28 20:34 UTC, eli1stark commented on lib/app/shared/features/kyc/view/components/empty_state/empty_state.dart
> +          state.countryNameSearch,
use `text` argument

2022-03-28 20:34 UTC, eli1stark commented on lib/app/shared/features/kyc/view/components/empty_state/empty_state.dart
> +
rename file to `empty_search_result.dart` and move under `lib/app/shared/components`

2022-03-29 10:27 UTC, Anton-Tesenchuk commented on lib/app/shared/features/kyc/view/components/empty_state/empty_state.dart
> +    final state = useProvider(kycCountriesNotipod);
done

2022-03-29 10:27 UTC, Anton-Tesenchuk commented on lib/app/shared/features/kyc/view/components/empty_state/empty_state.dart
> +class EmptyState extends HookWidget {
done

2022-03-29 10:27 UTC, Anton-Tesenchuk commented on lib/app/shared/features/kyc/view/components/empty_state/empty_state.dart
> +    Key? key,
done

2022-03-29 10:27 UTC, Anton-Tesenchuk commented on lib/app/shared/features/kyc/view/components/empty_state/empty_state.dart
> +          state.countryNameSearch,
done

2022-03-29 10:27 UTC, Anton-Tesenchuk commented on lib/app/shared/features/kyc/view/components/empty_state/empty_state.dart
> +
done

2022-03-29 12:31 UTC, merged