Add first 2 screens from login
MyJetWallet/Flutter.JetWallet pull request #56
Opened 2021-06-17 14:16 UTC by VovaMedvediev

2021-06-17 17:00 UTC, eli1stark requested changes
Good work, but needs some improvements

2021-06-18 07:22 UTC, eli1stark requested changes

2021-06-18 07:22 UTC, eli1stark commented on lib/auth/view/components/spot_outlined_button.dart
> +    final notifier = useProvider(authenticationNotipod.notifier);
try to make view abstract from state management

2021-06-18 14:13 UTC, VovaMedvediev commented on lib/auth/view/components/spot_outlined_button.dart
> +class SpotOutlinedButton extends HookWidget {
done

2021-06-18 14:13 UTC, VovaMedvediev commented on lib/auth/view/components/filled_button.dart
> +class SpotFilledButton extends StatelessWidget {
done

2021-06-18 14:13 UTC, VovaMedvediev commented on lib/auth/view/components/text_fields/email_text_field.dart
> +  String? _validate(String? value) {
refactored

2021-06-18 14:14 UTC, VovaMedvediev commented on lib/auth/view/components/text_fields/password_text_field.dart
> +  String? _validate(String? value) {
refactored

2021-06-18 14:14 UTC, VovaMedvediev commented on lib/main.dart
> +      // theme: appTheme,
removed

2021-06-18 14:14 UTC, VovaMedvediev commented on lib/auth/view/welcome.dart
> +            onTap: () => navigatorPush(
refactored

2021-06-18 14:14 UTC, VovaMedvediev commented on lib/auth/view/welcome.dart
> +            onTap: () => navigatorPush(
refactored

2021-06-18 14:14 UTC, VovaMedvediev commented on lib/auth/view/welcome.dart
> +                )),
refactored

2021-06-18 14:14 UTC, VovaMedvediev commented on lib/auth/view/welcome.dart
> +                )),
refactored

2021-06-18 14:14 UTC, VovaMedvediev commented on lib/auth/view/welcome.dart
> +          Expanded(child: Container()),
refactored

2021-06-18 14:14 UTC, VovaMedvediev commented on lib/auth/view/sign_in_sign_up.dart
> +                              isSignIn ? AuthScreen.signIn : AuthScreen.signUp);
refactored

2021-06-18 14:14 UTC, VovaMedvediev commented on lib/auth/view/sign_in_sign_up.dart
> +                      Expanded(child: Container()),
refactored

2021-06-18 14:14 UTC, VovaMedvediev commented on lib/auth/view/welcome.dart
> +          Expanded(child: Container()),
refactored

2021-06-18 14:14 UTC, VovaMedvediev commented on lib/auth/view/welcome.dart
> +          const Text(
refactored

2021-06-18 14:14 UTC, VovaMedvediev commented on lib/auth/view/sign_in_sign_up.dart
> +                        style: TextStyle(),
refactored

2021-06-18 14:14 UTC, VovaMedvediev commented on lib/auth/view/sign_in_sign_up.dart
> +                        style: TextStyle(),
refactored

2021-06-18 14:15 UTC, VovaMedvediev commented on lib/auth/view/sign_in_sign_up.dart
> +                      const Text(
left as it is

2021-06-18 14:15 UTC, VovaMedvediev commented on lib/auth/view/sign_in_sign_up.dart
> +                      const Text(
left as it is

2021-06-18 14:15 UTC, VovaMedvediev commented on lib/auth/view/components/spot_outlined_button.dart
> +    final notifier = useProvider(authenticationNotipod.notifier);
done

2021-06-18 14:35 UTC, merged