SPUI-1323 > Simplex in progress transaction info
MyJetWallet/Flutter.JetWallet pull request #593
Opened 2022-04-07 10:01 UTC by Anton-Tesenchuk

2022-04-20 15:01 UTC, VovaMedvediev commented on lib/app/shared/features/wallet/view/components/wallet_body/components/transactions_list_item/transaction_list_item.dart
> +                  transactionListItem.operationType,
and maybe this private method can be called "_iconFrom" so it looks like _iconFrom(transactionListItem.operationType).
Does this sounds better?

2022-04-20 15:01 UTC, VovaMedvediev commented on lib/app/shared/features/wallet/view/components/wallet_body/components/card_block/components/wallet_card_collapsed.dart
> +          if (
check formatting please

2022-04-20 15:01 UTC, VovaMedvediev commented on lib/app/shared/features/wallet/view/components/wallet_body/components/card_block/components/wallet_card_collapsed.dart
> +              (
same here

2022-04-20 15:02 UTC, VovaMedvediev commented on lib/app/shared/features/wallet/view/components/wallet_body/components/card_block/components/wallet_card.dart
> +          if (
formatting

2022-04-20 15:02 UTC, VovaMedvediev commented on lib/app/shared/features/wallet/view/components/wallet_body/components/card_block/components/wallet_card.dart
> +          if (
formatting

2022-04-20 15:02 UTC, VovaMedvediev commented on lib/app/shared/features/wallet/view/components/wallet_body/components/card_block/components/wallet_card.dart
> +                (currency.assetBalance == Decimal.zero &&
maybe it can be extracted to variable in build method or in private method in this Class with name "transactionInProgress".

2022-04-20 15:07 UTC, VovaMedvediev requested changes
requested changes

2022-04-20 15:07 UTC, VovaMedvediev commented on plugins/simple_kit/lib/src/asset_items/simple_wallet_item.dart
> +                  if (
actually, it is also can be extracted to variable/private method. The readability of this code will be better. If with a lot of conditions is hard to read

2022-04-20 15:07 UTC, VovaMedvediev commented on plugins/simple_kit/lib/src/asset_items/simple_wallet_item.dart
> +                          if (
actually, it is also can be extracted to variable/private method. The readability of this code will be better. If with a lot of conditions is hard to read

2022-04-20 15:07 UTC, VovaMedvediev commented on lib/app/shared/features/wallet/view/components/wallet_body/components/card_block/components/wallet_card_collapsed.dart
> +          if (
actually, it is also can be extracted to variable/private method. The readability of this code will be better. If with a lot of conditions is hard to read

2022-04-20 15:07 UTC, VovaMedvediev commented on lib/app/shared/features/wallet/view/components/wallet_body/components/card_block/components/wallet_card_collapsed.dart
> +              (
actually, it is also can be extracted to variable/private method. The readability of this code will be better. If with a lot of conditions is hard to read

2022-04-20 15:07 UTC, VovaMedvediev commented on lib/app/shared/features/wallet/view/components/wallet_body/components/card_block/components/wallet_card.dart
> +          if (
actually, it is also can be extracted to variable/private method. The readability of this code will be better. If with a lot of conditions is hard to read

2022-04-20 15:07 UTC, VovaMedvediev commented on lib/app/shared/features/wallet/view/components/wallet_body/components/card_block/components/wallet_card.dart
> +          if (
actually, it is also can be extracted to variable/private method. The readability of this code will be better. If with a lot of conditions is hard to read

2022-04-20 15:07 UTC, VovaMedvediev commented on lib/app/shared/features/wallet/view/components/wallet_body/components/card_block/components/wallet_card.dart
> +                (currency.assetBalance == Decimal.zero &&
actually, it is also can be extracted to variable/private method. The readability of this code will be better. If with a lot of conditions is hard to read

2022-04-21 06:56 UTC, Anton-Tesenchuk commented on plugins/simple_kit/lib/src/asset_items/simple_wallet_item.dart
> +                  if (
Done

2022-04-27 21:03 UTC, VovaMedvediev approved these changes

2022-04-27 21:04 UTC, merged