Feat/circle payment
MyJetWallet/Flutter.JetWallet pull request #626
Opened 2022-04-21 08:23 UTC by eli1stark

2022-04-27 21:25 UTC, VovaMedvediev requested changes

2022-04-27 21:25 UTC, VovaMedvediev commented on plugins/simple_kit/lib/src/fields/standard_field/public/simple_standard_field.dart
> +        enableinteractiveSelection: enableinteractiveSelection,
enableInteractiveSelection

2022-04-27 21:25 UTC, VovaMedvediev commented on lib/app/shared/features/payment_methods/view/payment_methods.dart
> +class _AddButton extends HookWidget {
why don't you move this widget to /components?

2022-04-27 21:25 UTC, VovaMedvediev commented on lib/app/shared/features/payment_methods/view/payment_methods.dart
> +            Navigator.pop(context);
Maybe it is better to use popUntil?

2022-04-27 21:25 UTC, VovaMedvediev commented on lib/app/shared/features/payment_methods/notifier/payment_methods_notifier.dart
> +        'Something went wrong! Try again',
Do we have localized error code for errors here?

2022-04-27 21:25 UTC, VovaMedvediev commented on lib/app/shared/features/add_circle_card/view/circle_billing_address/circle_billing_address.dart
> +class CircleBillingAddress extends HookWidget {
please try to extract smaller widgets from the CircleBillingAddress. A lot of curly braces in this file :)

2022-04-27 21:25 UTC, VovaMedvediev commented on lib/app/shared/features/add_circle_card/view/add_circle_card.dart
> +class AddCircleCard extends HookWidget {
same here

2022-04-28 06:04 UTC, eli1stark commented on plugins/simple_kit/lib/src/fields/standard_field/public/simple_standard_field.dart
> +        enableinteractiveSelection: enableinteractiveSelection,
done

2022-04-28 06:10 UTC, eli1stark commented on lib/app/shared/features/payment_methods/view/payment_methods.dart
> +class _AddButton extends HookWidget {
because I wanted to keep onTap logic close to the parent widget, but both ways can actually work, refactored to separate widget

2022-04-28 06:15 UTC, eli1stark commented on lib/app/shared/features/payment_methods/view/payment_methods.dart
> +            Navigator.pop(context);
If you use `popUntil` what condition to use? `popUntil` requires some condition to stop popping. If it was something like pop until root screen, it would be much easier to implement

2022-04-28 06:16 UTC, eli1stark commented on lib/app/shared/features/payment_methods/notifier/payment_methods_notifier.dart
> +        'Something went wrong! Try again',
No, we don't as far as I know

2022-04-28 06:32 UTC, eli1stark commented on lib/app/shared/features/add_circle_card/view/circle_billing_address/circle_billing_address.dart
> +class CircleBillingAddress extends HookWidget {
done

2022-04-28 06:33 UTC, eli1stark commented on lib/app/shared/features/add_circle_card/view/add_circle_card.dart
> +class AddCircleCard extends HookWidget {
done

2022-05-01 13:15 UTC, VovaMedvediev approved these changes

2022-05-01 13:15 UTC, VovaMedvediev commented
waiting for 1496 to be tested. If everything is ok then merge

2022-05-03 08:05 UTC, merged