SPUI-1441 > Fix Help Center icon + header
MyJetWallet/Flutter.JetWallet pull request #646
Opened 2022-04-29 13:37 UTC by VovaMedvediev

2022-05-02 05:35 UTC, eli1stark requested changes

2022-05-02 05:35 UTC, eli1stark commented on lib/app/screens/account/components/help_center_web_view.dart
> +    BuildContext context,
use named parameters here, it's more readable

2022-05-02 05:35 UTC, eli1stark commented on lib/app/screens/account/account.dart
> +                              navigatorPush(
use HelpCenterWebView.push(a1: a1, a2: a2) instead

2022-05-03 09:49 UTC, VovaMedvediev commented on lib/app/screens/account/components/help_center_web_view.dart
> +    BuildContext context,
refactored

2022-05-03 09:49 UTC, VovaMedvediev commented on lib/app/screens/account/account.dart
> +                              navigatorPush(
refactored

2022-05-04 07:40 UTC, merged