SPUI-1656 > Правки по сепаратору на экране Sell
MyJetWallet/Flutter.JetWallet pull request #701
Opened 2022-05-19 19:04 UTC by gravio-inv

UI - Правки по сепаратору на экране Sell - choose destination, в флоу Convert при выборе другого ассета

2022-05-20 08:06 UTC, VovaMedvediev reviewed
Translate PR name to English

2022-05-20 09:06 UTC, eli1stark commented
And provide description in English as well

2022-05-23 06:42 UTC, eli1stark requested changes
The same issue as with SPUI-1648, please provide a descriptive name of this pr and in the future as well.

2022-05-23 06:43 UTC, eli1stark requested changes

2022-05-23 06:43 UTC, eli1stark commented on plugins/simple_kit/lib/src/asset_items/simple_asset_item.dart
> +                  //padding: const EdgeInsets.symmetric(vertical: 10.0),
remove comment

2022-05-23 06:43 UTC, eli1stark commented on plugins/simple_kit/lib/src/asset_items/simple_asset_item.dart
> +                  padding: const EdgeInsets.only(top: 10.0, bottom: 10),
provide trailing comma

2022-05-24 13:57 UTC, VovaMedvediev approved these changes

2022-05-25 03:44 UTC, merged