Add requests signing
MyJetWallet/Flutter.JetWallet pull request #83
Opened 2021-07-06 12:24 UTC by VovaMedvediev

2021-07-07 08:15 UTC, eli1stark requested changes

2021-07-07 08:15 UTC, eli1stark commented on lib/shared/helpers/refresh_token.dart
> +      refreshToken + (serverTimeString ?? ''),
Rethink this flow please

2021-07-07 08:15 UTC, eli1stark commented on pubspec.yaml
> +  fast_rsa: ^1.3.6
Move to "OTHER" section:
`fast_rsa: ^1.3.6 # RSA signing`

2021-07-07 08:15 UTC, eli1stark commented on pubspec.yaml
> +  - packages/fast_rsa/web/assets/worker.js
Add comment: `// [Start] fast_rsa  -> ... <- fast_rsa [End]`

2021-07-07 08:17 UTC, eli1stark commented on pubspec.yaml
> +  fast_rsa: ^1.3.6
And add the latest version (2.0.1) with support of null-safety

2021-07-14 08:08 UTC, VovaMedvediev commented on lib/service/services/authentication/model/authenticate/login_request_model.dart
> +    required String publicKeyPem,
done

2021-07-14 08:08 UTC, VovaMedvediev commented on lib/shared/helpers/refresh_token.dart
> +    final serverTimeString = serverTime.data?.value.now.toString();
done

2021-07-14 08:08 UTC, VovaMedvediev commented on lib/shared/services/rsa_service.dart
> +  static const int _bits = 2048;
done

2021-07-14 08:08 UTC, VovaMedvediev commented on lib/shared/services/local_storage_service.dart
>  const refreshTokenKey = 'refreshTokenKey';
done

2021-07-14 08:08 UTC, VovaMedvediev commented on lib/shared/dio/helpers/add_signing.dart
> +            privateKey ?? '',
done

2021-07-14 08:08 UTC, VovaMedvediev commented on lib/shared/helpers/refresh_token.dart
> +      privateKey ?? '',
done

2021-07-14 08:08 UTC, VovaMedvediev commented on lib/shared/helpers/refresh_token.dart
> +      refreshToken + (serverTimeString ?? ''),
added api for getting server time via rest

2021-07-14 08:08 UTC, VovaMedvediev commented on pubspec.yaml
> +  fast_rsa: ^1.3.6
done (3.0.0)

2021-07-14 08:08 UTC, VovaMedvediev commented on pubspec.yaml
> +  - packages/fast_rsa/web/assets/worker.js
done

2021-07-14 10:08 UTC, merged